### PR TITLE
Fix bug related to diffusion coef in AdvDiffSemiImplicit class

### PR DESCRIPTION
**Pull request by Raamkrishnan**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [x] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

I have updated the diffusion coefficient in integrateHierarchy with the new values. Now I initialize the LHS and RHS of the adv diff equation in the integrateHierarchy and preprocessIntegrateHierarchy, respectively. Please take a look. All the existing adv_diff tests pass with this patch. I can also add a new test if you have any suggestions.

### CODE REVIEW

**Comment by Raamkrishnan** [comment]
Sorry there is a small bug. Let me correct it now

**Comment by amneetb** [comment]
@Raamkrishnan : this looks good to me. 

@boyceg: Please take a look.

@drwells : There are some tests failing due to a change in logging messages in the output of these tests (some blocks of code were moved in this PR, causing this change). When you and Boyce are happy with this PR, Rama can adjust those failing tests' outputs.

**Review by amneetb — APPROVED** [review]

**Comment by boyceg** [comment]
Looks good. Just to confirm: this still only re-initializes when the coefficients or time step size changes?

**Comment by amneetb** [comment]
Yes. Reinitializes the coefficients and solvers.

**Comment by drwells** [comment]
This looks good - can you add a test which failed before this PR but passes now?

**Comment by amneetb** [comment]
@drwells: Nothing was failing before. This PR improves the time accuracy of the scheme when diffusion coefficients are varying in time. Most/all of the IBAMR examples were with constant diffusion coefficients. 

(We are doing heat transfer problems and this requires time varying coefficients. We noticed this bug and hence fixed it.)

**Review by drwells — APPROVED** [review]

**Comment by amneetb** [comment]
@Raamkrishnan : Please update the output of the failing tests. These are just text-related mismatch, I think. Once that is done, David can take a final look at the changed output of the tests and merge this PR.

**Comment by Raamkrishnan** [comment]
I have updated the tests/IBTK/hierarchy_callbacks.output. Since I moved the initialization of linear solvers to integrateHierarchy, this test was failing with text mismatch. Now this is good to merge.

**Review by drwells — APPROVED** [review]

**Pull request merged**
