### PR TITLE
Refactor jacobian calculator

### PR DESCRIPTION
**Pull request by drwells**
We added a new class `IBTK::Mapping` in #961, which provided a superset of the functionality of `JacobianCalculator`. This PR finally cleans up the implementation to just use `Mapping` everywhere.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
That's a good idea but its also a preexisting problem. Let me open an issue so we remember to do that but I would prefer to not fix it in this PR (i.e., this PR's purpose should be to just get rid of `JacobianCalculator`).

**Comment by boyceg** [comment]
> That's a good idea but its also a preexisting problem. Let me open an issue so we remember to do that but I would prefer to not fix it in this PR (i.e., this PR's purpose should be to just get rid of `JacobianCalculator`).

But isn't this also the PR where the class name "`Mapping`" is introduced in the first place? Why not fix it now before merging?

**Comment by drwells** [comment]
> But isn't this also the PR where the class name "Mapping" is introduced in the first place? Why not fix it now before merging?

Yes and no. We previously had the following compatibility shim:

```cpp
 class NodalMapping : public Mapping<dim, spacedim>, public JacobianCalculator
```
i.e., all the `Mapping` classes we actually used also were `JacobianCalculator`s so that we could start implementing all these new `Mapping` classes without changing how we use `JacobianCalculator` in older code.

**Comment by drwells** [comment]
If you think it would be easier to add those changes to this PR I will do so - I think it would be easier to keep it separate so that the inheritance changes are not mixed in with the mass renaming operations.

**Comment by boyceg** [comment]
> > But isn't this also the PR where the class name "Mapping" is introduced in the first place? Why not fix it now before merging?
> 
> Yes and no. We previously had the following compatibility shim:
> 
> ```c++
>  class NodalMapping : public Mapping<dim, spacedim>, public JacobianCalculator
> ```
> 
> i.e., all the `Mapping` classes we actually used also were `JacobianCalculator`s so that we could start implementing all these new `Mapping` classes without changing how we use `JacobianCalculator` in older code.

I had missed that `Mapping` already showed up. I agree; let's change the name in another PR.

**Pull request merged**
