### PR TITLE
Updating VC examples

### PR DESCRIPTION
**Pull request by nishantnangia**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

This PR is large, but it only touches examples using the variable-coefficient INS solver. I went through and made sure each example had appropriate level set initial conditions specified, which is important if an initial (density-weighted) divergence-free projection occurs.

Moreover, I went through and made sure each example's spatial and temporal resolutions matches those in our published work. Finally, there are some small bug fixes for broken examples and incorrectly named log files.

### CODE REVIEW

**Comment by nishantnangia** [comment]
Looks like I got PR #1000 :-)

**Comment by amneetb** [comment]
Thanks @nishantnangia, and congrats on PR #1000  🎉  

@drwells : We would want to merge these PRs into master before adding some Brinkman penalization code in AdvDiffHI, which one of the IBAMR user needs for simulating heated particle settling problems.

**Comment by abarret** [comment]
> Looks like I got PR #1000 :-)

Just 24 to go until a big round-number milestone :).

**Comment by abarret** [comment]
It would be nice to get rid of all of these vertex, spring, etc files and have them generated as needed, i.e. #560. That would allow us to eliminate almost one million lines, which is nearly 40 percent of our current line count:

`find . -regextype awk -regex ".*\.(spring|vertex|target|beam|rod|director|xspring|anchor|mass|inst|source)" | xargs wc -l`
outputs
`1045364 total`

where as
`git ls-files | xargs cat | wc -l`
outputs
`2601183`

**Comment by nishantnangia** [comment]
Sure, I can go ahead and do this for the multiphase_flow and wave_tank examples for this PR.

**Comment by abarret** [comment]
I think that's outside the scope of this PR and we should merge as is

**Comment by abarret** [comment]
Unless @drwells or @boyceg have a different opinion, I suggest we leave this as is, and let #560 take care of replacing these vertex files. 

I'll merge tomorrow morning unless I hear otherwise.

**Comment by nishantnangia** [comment]
Also fine by me :)

**Comment by amneetb** [comment]
@abarret : ping 😊

**Comment by abarret** [comment]
Whoops. It seems like nobody has any concerns, so let's merge as is.

**Pull request merged**
