### PR TITLE
Multilevel ibfe 1

### PR DESCRIPTION
**Pull request by drwells**
We need to fundamentally change the way we set up the patch-to-element mapping to support multilevel interaction in IBFE. It's not backwards-compatible, but we can make our lives a lot easier by just getting rid of all the extra `FEDataManager::getManager()` overloads so that we can set up the block id to patch level mapping just once.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Review by boyceg — COMMENTED** [review]
General comment --- I have not checked every instance carefully, but I would prefer to use `max_level_number` to identify the maximum level number, and `max_levels` to indicate the maximum _number_ of levels. Note that `max_levels = max_level_number + 1`. It looks like there are a few places where `max_level_number` was changed to `max_levels`.

**Comment by drwells** [comment]
Good point - let me fix that.

**Comment by boyceg** [comment]
It looks like this is done consistently, so I'm not sure if there is anything to fix.

**Comment by drwells** [comment]
I improved the status quo but some of the function argument names are wrong.

**Comment by drwells** [comment]
That should fix things - the first commit now should always use `max_levels` but internally store `d_finest_level_number`. I think `d_finest_level_number` is more commonly used than `d_max_level_number` but its not consequential - we can change it if we want.

**Review by boyceg — APPROVED** [review]

**Comment by boyceg** [comment]
I usually think of `finest_level_number` as the finest level currently in the patch hierarchy, and `max_level_number` as the finest possible level number. In most use cases, these are the same. However, if we let folks assign different structures (or parts of structures) to different levels, then we could have models where the structures are not on the finest level of the patch hierarchy.

**Comment by boyceg** [comment]
Specifically, you could set up something where feature detection criteria dynamically add or remove AMR grid levels that are finer than the finest level that a structure lives on.

**Comment by drwells** [comment]
that's a good distinction to make (and its relevant here since FEDataManager will, currently, tag cells when we set up the hierarchy and there are no patches on `d_finest_level_number`). Let me update those names to make this clearer.

**Comment by boyceg** [comment]
If users actually specify which levels they want to assign structures to, then there actually is not need to pass in `max_levels` or `max_level_number` to `FEDataManager`.

**Comment by boyceg** [comment]
OTOH, because `FEDataManager` is partially responsible for setting up the AMR grid, it needs to know how "deep" the structures should go in the patch hierarchy.

**Comment by drwells** [comment]
> OTOH, because FEDataManager is partially responsible for setting up the AMR grid, it needs to know how "deep" the structures should go in the patch hierarchy.

Yes - I am pretty sure that we need to have this value available in the case where we tag cells and the user does not specify which patch levels elements should be on.

**Comment by boyceg** [comment]
Anyway, you may notice that there are a number of places in the code that update the equivalents of `coarsest_patch_level_number` and `finest_patch_level_number` based on the actual configuration of the `PatchHierarchy`.

**Comment by drwells** [comment]
I added one more commit where I rename things, when relevant, to `max_patch_level`.

**Review by boyceg — APPROVED** [review]

**Pull request merged**
