### PR TITLE
Updates to PETSc 3.7, libMesh 1.0.0

### PR DESCRIPTION
**Pull request by boyceg**

### CODE REVIEW

**Comment by boyceg** [comment]
@deleeke This PR requires different versions of PETSc and libMesh than are currently being used in Jenkins.

**Comment by boyceg** [comment]
@deleeke Also, once this is merged, it will be necessary to update the configuration instructions to reflect the required versions of these libraries.

**Comment by deleeke** [comment]
I can build those new versions today and update the Jenkins configure script.

**Comment by deleeke** [comment]
retest this please

**Comment by deleeke** [comment]
@boyceg I have an updated version of the Linux build instructions ready for whenever this gets merged to master.

**Comment by boyceg** [comment]
jenkins retest this please

**Comment by boyceg** [comment]
@deleeke should Jenkins be working for this branch or not?

**Comment by deleeke** [comment]
@boyceg I changed the configure script in the Jenkins build to use the 3.7.2 build and the 1.0.0 libmesh build (without the unique pointer) before I commented "retest this please".  I haven't gotten to investigate why it failed. This same branch was successful in my fork at https://github.com/DevOpTester/IBAMR/pull/10

**Comment by deleeke** [comment]
@boyceg It was failing during compilation in a way that does not occur in a clean directory, so I cleaned out the workspace and am going to try it again now.

Jenkins, retest this please

**Pull request merged**
