### PR TITLE
Replace std::ostringstream with std::to_string (2) Issue #388

### PR DESCRIPTION
**Pull request by jabrown893**
This pull request addresses occurrences of Issue #388 in the ibtk/src folder.

### CODE REVIEW

**Comment by boyceg** [comment]
Looks good to me. @drwells, do you want to take a quick look before merging?

**Comment by boyceg** [comment]
@drwells, shall we merge?

**Comment by drwells** [comment]
Sorry! I promise that I will do this at some point today. It is almost surely fine.

**Comment by drwells** [comment]
Let me do this now so I can move on with my life.

**Comment by drwells** [comment]
Thanks a lot @jabrown893 !

**Pull request merged**
