### PR TITLE
update generated files using automake 1.16.2

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
Homebrew updated my automake to 1.16.2 ...

**Comment by drwells** [comment]
This was just realized on Sunday - the Homebrew team really has their act together!

I will update to this soon on my personal machines and its not too hard to get it on other devices I frequently use but this is going to make contributing harder for most people with older tool sets. Can we also update the 'download autotools' script to install this new version to ease the pain?

**Comment by boyceg** [comment]
I could try to figure out how to downgrade.

The bootstrap script actually only checks that the version and subversion number match --- so it is only checking to see if you are using autoconf 1.16. Maybe it needs to be updated to pin down the full version number?

**Comment by drwells** [comment]
We will need to given that there are nontrivial output differences.

**Comment by boyceg** [comment]
Right now the `bootstrap` script checks to see if minimum version requirements are met. How much work would it be to make it check that a precise version is being used?

**Comment by drwells** [comment]
It's not hard. In fact, the current version check only looks at the minor version, not the major or subminor versions. I'm writing a patch.

**Comment by boyceg** [comment]
OK, great. We should just standardize specific tools.

**Comment by abarret** [comment]
The bundled automake needs to be updated as well. Or we need to update the script to download the correct configure tools

**Comment by boyceg** [comment]
Let's stick with `automake` 1.16.1 for now and handle updates in concert with specifying versions of tools in `bootstrap`, per #945.

**Pull request closed without merging**
