### PR TITLE
include normal vector in surface function API

### PR DESCRIPTION
**Pull request by boyceg**

### CODE REVIEW

**Comment by boyceg** [comment]
@cpuelz @rossisimone this PR adds normal vectors to the surface force API. Note that the normal vector is in the reference configuration. If you need the vector in the current configuration, you will need to transform it using Nanson's relation. (Maybe there should be a helper function to do this?)

**Comment by cpuelz** [comment]
if its easiest enough, then it could be nice to have both reference and current vectors to be consistent with the current API for positions...

**Comment by boyceg** [comment]
@cpuelz check this out --- it now includes both reference and current normal vectors. I put them before the deformation gradient FF since somehow they seemed related. What do you think of the interface?

**Comment by cpuelz** [comment]
looks good to me!

**Pull request merged**
