### PR TITLE
Replaced UniquePtr with unique_ptr

### PR DESCRIPTION
**Pull request by abarret**
Follow up to #403. Replace all instances of `LibMesh::UniquePtr` with `std::unique_ptr`. A perl script is provided in the scripts directory.

If we want to keep using the Libmesh alias we can close this. I won't be offended :)

### CODE REVIEW

**Comment by boyceg** [comment]
Looks good to me; let's merge once Jenkins is happy.

Although this PR gives you a net increase in LOC. ;-)

**Comment by abarret** [comment]
Sure. How about `replaceLibmeshPointers.pl`? `libMesh::AutoPtr` is not used anywhere in IBAMR, but I thought I would include it for completeness. I could also just remove the `AutoPtr` replacement.

> Although this PR gives you a net increase in LOC. ;-)

I figured I could add a few and still be under the 331,000 lines deleted...

**Comment by boyceg** [comment]
Sounds good.

**Comment by abarret** [comment]
Done and rebased.

**Pull request merged**
