### PR TITLE
adding "first class" support for B-spline kernel functions

### PR DESCRIPTION
**Pull request by boyceg**

### CODE REVIEW

**Comment by boyceg** [comment]
@amneetb please take a look.

**Comment by boyceg** [comment]
@amneetb do you also have the formula handy for the 6-point spline? I'd like to add it too.

**Comment by amneetb** [comment]
I can check files on my computer to see till how far I went.

**Comment by amneetb** [comment]
Here it is:

x^5/120	0<=x<1
1/120 (-6 (-1+x)^5+x^5)	1<=x<2
1/120 (15 (-2+x)^5 -6 (-1+x)^5 + x^5)	2<=x<3
1/120 (15 (4-x)^5  - 6 (5-x)^5  + (6-x)^5)	3<=x<4
1/120 (-6 (5-x)^5  +  (6-x)^5)	4<=x<5
1/120 (6-x)^5	5<=x<=6


You would shift the origin by 3. See main.cpp for example

**Comment by boyceg** [comment]
Can you work out the code/formula in the same format as in the application where we prototyped this stuff?

**Comment by amneetb** [comment]
Sure. For efficiency I just expanded the powers. Would you recommend this or something else for this long polynomials .e.g r^3 = r*r*r or pow(r,3)?

**Comment by boyceg** [comment]
Just do it like you did for the 3-, 4-, and 5-point. You can see what I did to try to reduce the number of computations in the PR, although I would like to try to get rid of the conditionals.

**Comment by amneetb** [comment]
function lagrangian_bspline_6_delta(x)
 
        implicit none
        double precision lagrangian_bspline_6_delta,modx,r,r2,r3,r4,r5,x
 
        modx = dabs(x)
        r = modx + 3.d0;
        r2 = r*r
        r3 = r2*r
        r4 = r3*r
        r5 = r4*r
       if (modx .le. 1.d0) then
          lagrangian_bspline_6_delta = (1.d0/60.d0)* (2193.d0 - 
      & 3465.d0*r + 2130.d0*r2 - 630.d0*r3 + 90.d0*r4 - 5.d0*r5)
       elseif (modx .le. 2.d0) then
          lagrangian_bspline_6_delta = (1.d0/120.d0)* (-10974.d0 +
      &  12270.d0*r - 5340.d0*r2 + 1140.d0*r3 - 120.d0*r4 + 5.d0*r5)
       elseif (modx .le. 3.d0) then
          lagrangian_bspline_6_delta = (1.d0/120.d0)*(7776.d0 - 
      &  6480.d0*r + 2160.d0*r2 - 360.d0*r3 + 30.d0*r4 - r5)
       else
          lagrangian_bspline_6_delta = 0.d0
       endif
 
       return
       end

**Comment by boyceg** [comment]
OK, the 6-point kernel seems to work too.

**Comment by boyceg** [comment]
retest this please

**Comment by boyceg** [comment]
retest this please

**Comment by boyceg** [comment]
retest this please

**Comment by amneetb** [comment]
I take you are asking Jenkins to retest it and not me, right?

**Comment by boyceg** [comment]
Yes. Although if you have reviewed the PR then I will go ahead and merge it. :-)

**Comment by amneetb** [comment]
Yes, I have reviewed it although not too thoroughly.

**Pull request merged**
