### PR TITLE
synch coarse grid values with overlying fine grid data in IBFEMethod::interpolateVelocity()

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
I looked at this earlier and I came to the conclusion that "if the scratch hierarchy works without doing this then its probably not necessary" but we should definitely test that assumption.

**Comment by boyceg** [comment]
I think that it is good practice to resynch just in case a different coarsen operator was used. We don't require coarsen operators to be consistent in different places, so it is possible (albeit unlikely) that the coarse grid data were set using some other coarsen operator.

As a specific example --- we are about to try to switch to using RT0-based coarsening for multilevel IBFE, but that is not what we want to use for the incompressible flow solvers.

**Comment by boyceg** [comment]
I just confirmed that the current IBFE tests. (I know that you are updating the multilevel tests.)

**Comment by boyceg** [comment]
@drwells would you prefer that we handle restricting internally in `IBFEMethod`, as is now done for prolongation?

**Comment by boyceg** [comment]
I am happy to do it either way, but I am about to start mucking around with the way that we do coarsening for multilevel IBFE.

**Comment by drwells** [comment]
That's a good question. I would prefer that the Navier-Stokes solver correctly set the velocity on all levels whenever it sets a value in the hierarchy so that its not up to a class like IBFEMethod which should, in principle, just be reading those values. If we want to do something else inside IBFEMethod we should use a scratch index.

**Comment by boyceg** [comment]
We already do use a scratch index --- the velocity is interpolated from a copy of the velocity from the fluid solver, since in general the fluid solver does not have the right ghost cell widths.

**Comment by boyceg** [comment]
(Similarly, forces are spread to a scratch index, for similar reasons.)

**Comment by boyceg** [comment]
The way this was supposed to work was that `IBHierarchyIntegrator` (or a subclass) handles setting up communication schedules, so that the IB implementations don't need to mess with them --- but instead just use them "in the right way".

`IBFEMethod` effectively maintains its own patch hierarchy, however, and so it cannot use the provided refine schedule for spreading.

I guess I am wondering if it would be clearer for it also not to use the provided coarsen schedule for interpolating. Using the provided coarsen schedule splits up the specification of the interlevel transfer operators between the `IBHierarchyIntegrator` and the `IBStrategy`, which does not seem ideal.

**Comment by drwells** [comment]
> IBFEMethod effectively maintains its own patch hierarchy, however, and so it cannot use the provided refine schedule for spreading.

Even if it did not due to the way we now accumulate forces (which is necessary for efficiency reasons) we really do need to put all the IBFE-specific forces into a separate privately managed index.

> Using the provided coarsen schedule splits up the specification of the interlevel transfer operators between the IBHierarchyIntegrator and the IBStrategy, which does not seem ideal.

It seems to me that `IBHierarchyIntegrator` should be in charge here. In particular, if we have multiple IBStrategy objects, they are going to each repeat the same communication, or (like in this case) overwrite values in a difficult to understand way.

**Comment by drwells** [comment]
I rebased this against master and all the tests still pass. I'm not convinced that this is necessary but it doesn't hurt - it also makes sense to do this if we are also going to execute the other schedules.

**Review by drwells — APPROVED** [review]
Let's add this for the sake of consistency. If it shows up a lot in profiling (which is unlikely) we can easily revert it later.

**Pull request merged**
