### PR TITLE
Higher order element support in get_max_edge_length

### LINKED ISSUE #668: Implement max_edge_length for higher order elements
From our meeting today: we should implement this by linearizing element edges with line segments and calculating the sum of their lengths.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #668.

The test output changed because instead of the old algorithm (where we find the maximum distance between two nodes with a common edge) we find the lengths of both line segments and add them together.

### CODE REVIEW

**Comment by boyceg** [comment]
Does this affect performance any?

**Comment by drwells** [comment]
It should help a lot. I'll check.

**Comment by drwells** [comment]
On my little benchmark (IBFE/explicit/ex4/main3d with `Hex27` elements and 5 time steps) we go from 687 million instructions in `getQuadratureKey` to 110 million instructions. Its a bit less than 1% of the total instruction count.

**Comment by drwells** [comment]
@boyceg are you happy with this? If so lets merge.

**Pull request merged**
