### PR TITLE
Fixing small bug in VC Gauss-Seidel smoothers

### PR DESCRIPTION
**Pull request by nishantnangia**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

This PR fixes a small bug I discovered in the VC Gauss-Seidel Fortran kernels, although it doesn't seem to have any appreciable effect on solver convergence for any of the examples/tests that actually use this routine. All the tests pass except `adv_diff/adv_diff_01_2d.input`.

I couldn't think of a good test for this change, but open to suggestions. I'm also fine with merging as-is.

### CODE REVIEW

**Comment by amneetb** [comment]
Approved.

**Comment by boyceg** [comment]
Maybe should figure out the failing test before merging.

**Comment by nishantnangia** [comment]
There is currently an open issue for that test, which states that it’s non
deterministic.

**Comment by drwells** [comment]
All the tests pass locally for me.

I am a little worried that no one else merged this, if the tests are all known to pass. Is there something we were waiting for?

**Pull request merged**
