### PR TITLE
add standalone explicit dynamics solver

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
@drwells this is still very much WIP, but I wanted to be able to use `LibMeshSystemVectors` in cases where there are not corresponding `FEDataManager`s. Let me know what you think about the changes made here to `LibMeshSystemVectors`.

**Comment by drwells** [comment]
I think it would make more sense to tackle this with inheritance instead of having two different ways in which this class can operate - e.g., we could make the current (on master) implementation `LibmeshIBSystemVectors` with a different constructor (and also have it offer the IB functions) and then make the 'new' class here the base class (which takes the array of `EquationSystems` in its constructor instead).

**Comment by boyceg** [comment]
@drwells, how about this? If you are happy with this, I will squash and cherry pick into a separate PR.

**Comment by boyceg** [comment]
I split off the changes to `LibMeshSystemVector` in #967.

**Pull request closed without merging**
