### PR TITLE
Force ghosted assembly

### PR DESCRIPTION
**Pull request by drwells**
From the heart model meeting - this makes a marginal performance difference (maybe 0.25% improvement?) but it should make things more consistent in parallel. It also shows how we can modify other systems if necessary to use the same tricks.

### CODE REVIEW

**Comment by boyceg** [comment]
Can we also / do we need to do this in `FEDataManager::computeL2Projection()`?

**Comment by drwells** [comment]
Do you mean `interpWeighted`? We already do ghosted assembly there - see #557.

**Comment by boyceg** [comment]
Yeah.

Is this the only place left in the code at present where we do FE-type assembly without using ghosts?

**Comment by drwells** [comment]
Surprisingly it is - except for the non-default behavior we left in for velocity interpolation.

**Comment by drwells** [comment]
On second thought - I'm not sure. We still call `VecAssemblyBegin` in `CIBMethod`, `CIBStrategy`, and a few other places. I'm not sure if we are relying on `VecStash or not for those.

**Comment by boyceg** [comment]
Ah, I really mean to be asking if this is the only place where we do FE-type assembly in `IBFEMethod` and friends.

**Comment by drwells** [comment]
I believe so - we don’t have any mandatory communication in FEDataManager. We definitely do use ‘PetscVector::close()’ in IBFESurfaceMethod but we can’t really change things there without conflicting with #828.

**Pull request merged**
