### PR TITLE
rename SPECIALIZED_CONSTANT_REFINE as RT0_REFINE

### PR DESCRIPTION
**Pull request by boyceg**

### CODE REVIEW

**Comment by boyceg** [comment]
@drwells, can you check out the associated FORTRAN kernels to make sure I am not misreading what they are doing? :-D

**Comment by drwells** [comment]
Sure.

**Comment by boyceg** [comment]
I think we possibly could use this instead of the horrible `CartSideDivPreservingRefine` operator.

**Comment by boyceg** [comment]
@amneetb, not that `RT0Refine` (formerly `SPECIALIZED_CONSTANT_REFINE`) will ensure that discrete divergence is preserved in the ghost cell region along the coarse-fine interface without any extra fix-up

**Comment by drwells** [comment]
The FORTRAN kernel looks fine. I will write a little followup PR where I will adapt #584 for refinement to really verify this kernel.

@boyceg could you, for the sake of record, add a little changelog entry under `incompatibilities`?

**Comment by drwells** [comment]
Thanks!

**Comment by boyceg** [comment]
I am about to catch a flight. If I don't beat you to it, free to merge once Jenkins gives the 👍.

**Comment by drwells** [comment]
Will do! I want to merge it so that I can immediately write the followup PR with a nice new test.

**Comment by drwells** [comment]
Doing the simplest thing I could for the test still causes infinite values in the output.

**Pull request merged**
