### PR TITLE
Add libmesh exodus check

### LINKED ISSUE #272: Check for Exodus support in libmesh during configuration
The IBFE examples (and other things) assume that this is available, but we do not check that libmesh is compiled with this feature. We should add a check to `configure_libmesh.m4` to verify that it is turned on.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #272.

### CODE REVIEW

**Comment by drwells** [comment]
Per discussion in #272, I removed the commit that modifies IBFEInstrumentPanel.

**Comment by boyceg** [comment]
jenkins retest this please

**Comment by boyceg** [comment]
jenkins retest this please

**Comment by boyceg** [comment]
(Sorry for the noise, but I am trying to wipe out some temporary directories on the Jenkins server...)

**Comment by boyceg** [comment]
It looks like there is a ConstraintIB example that is not working in Jenkins.

**Comment by boyceg** [comment]
Jenkins retest this please

**Comment by boyceg** [comment]
It seems like it is something about the way that the parallel build of the examples that is messing up Jenkins. When I re-run the tests, they seem to make it further...

**Comment by boyceg** [comment]
Indeed, rerunning the tests allows them to succeed. Not ideal ... :-(

**Comment by drwells** [comment]
> the way that the parallel build of the examples that is messing up Jenkins>

One of these days I will make a build system modification that will work on the first try. Is there an error message or something else that I could look at to try and fix this?

**Pull request merged**
