### PR TITLE
Adding fully Eulerian version of IBLevelSet/ex0 to IBLevelSet/ex2

### PR DESCRIPTION
**Pull request by amneetb**
Also using Hypre level solver in the pressure preconditioner for IBLevelSet examples. It performs much better with large contrasting ratios. 

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by amneetb** [comment]
@Kaustubh-Khedkar : Can you run this example (ex2) and ex0 and compare the rigid body dynamics? This also fixes the initial tagging issue for both the solid and the gas-liquid interface (by relying on `LevelSetInitialConditions`).

**Comment by drwells** [comment]
Nice work. Lets go ahead and merge soon.

Would you mind adding both a changelog entry and setting things up to work with CMake? For the later, you can copy and paste `IBLevelSet/ex0/CMakeLists.txt` into the other directories, update it, and then list the examples in `IBLevelSet/CMakeLists.txt`.

**Comment by amneetb** [comment]
Sure! Will do once @Kaustubh-Khedkar verifies that it is producing the correct output.

**Comment by drwells** [comment]
I'd like to get this in the next release. Can you guys get everything in order by early January?

**Comment by amneetb** [comment]
@drwells : The results match well between the two examples. So it is ready to go from our end. Can you take care of the CMake stuff? I'm not familiar with it.

**Comment by drwells** [comment]
Nice plots and yes!

**Review by drwells — APPROVED** [review]

**Pull request merged**
