### PR TITLE
add additional composite B-spline kernel functions

### PR DESCRIPTION
**Pull request by boyceg**
Adds 5/4 and 6/5 composite B-splines.

### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
@drwells, @abarret, could one of you help me to figure out why these tests are failing? I cannot reproduce locally 😿

**Comment by drwells** [comment]
Interesting problem. In `exact` mode `interpolate_01` should just print `OK` at the end but it also printed

```

    ##2       ==> 0.48555, 0.390822, 0.346354, 1.52145e-12
```
The last column is the error: `1.52e-12`. The problem is here:

https://github.com/IBAMR/IBAMR/blob/171f7499849321bb99c65fb589f888e56504ecfb/tests/interpolate/interpolate_01.cpp#L207-L210

That line needs to be updated to
```cpp
const double tol = LEInteractor::getStencilSize(interp_fcn) > 4 ? 1e-10 : 1e-12;
```
or something nearby to lower the error tolerance enough for the stencils to pass. This presumes that these stencils can exactly reproduce a bilinear field which I think they should do.

**Comment by drwells** [comment]
I'm not sure why the CI testers exhibit more error than my desktop - these tests pass for me too. Must be different optimization levels.

**Comment by boyceg** [comment]
@drwells tests all pass now.

**Review by drwells — APPROVED** [review]

**Pull request merged**
