### PR TITLE
Improve an error message.

### PR DESCRIPTION
**Pull request by drwells**
Actually give some useful advice on how to fix the problem @cpuelz asked about over the weekend.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Review by boyceg — APPROVED** [review]

**Comment by cpuelz** [comment]
thanks!

**Comment by cpuelz** [comment]
is it ```regrid_cfl_interval``` or ```regrid_fluid_cfl_interval```? I was looking at the input file for the ```IIMethod``` ex7

**Comment by drwells** [comment]
Both work (see IBHierarchyIntegrator.cpp):
```cpp
    if (db->keyExists("regrid_cfl_interval")) d_regrid_fluid_cfl_interval = db->getDouble("regrid_cfl_interval");
    if (db->keyExists("regrid_fluid_cfl_interval"))
        d_regrid_fluid_cfl_interval = db->getDouble("regrid_fluid_cfl_interval");
    if (db->keyExists("regrid_structure_cfl_interval"))
        d_regrid_structure_cfl_interval = db->getDouble("regrid_structure_cfl_interval");
```
but we should avoid writing `regrid_cfl_interval` since it does not refer to which CFL condition it uses.

**Comment by drwells** [comment]
I'm going to edit the example input files to clean this up - I'll open a new issue for it.

**Pull request merged**
