### PR TITLE
allow users to set outflow_bdry_extrap_type in AdvDiffWavePropConvectiveOperator

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
@abarret can you add some tests? :-D

**Comment by abarret** [comment]
> @abarret can you add some tests? :-D

Sure. I'll do that later tonight.

**Comment by abarret** [comment]
For some reason, I'm getting error that is an order of magnitude higher when I use `outflow_bdry_extrap_type = "CONSTANT"`. I'm investigating.

**Comment by boyceg** [comment]
I think that `outflow_bdry_extrap_type = "CONSTANT"` should be equivalent to `outflow_bdry_extrap_type = "NONE"` + homogeneous Neumann BCs.

**Comment by abarret** [comment]
That seems to be the case. Using `outflow_bdry_extrap_type = "NONE"` + homogeneous Neumann BCs gives the same errors as `outflow_bdry_extrap_type = "CONSTANT"`.

**Comment by boyceg** [comment]
Great. Can you add tests for both? :-)

**Comment by abarret** [comment]
Hmm I think I spoke too soon. The errors are the same for `CUI` and `CENTERED`, but using "WAVE_PROP" and "PPM" using `outflow_bdry_extrap_type = "NONE"` + homogeneous Neumann BCs gives errors that are about 40% smaller when compared against `outflow_bdry_extrap_type = "CONSTANT"`

**Comment by boyceg** [comment]
👎 Sounds like a possible bug.

**Comment by boyceg** [comment]
Although maybe not a bug per se --- `"PPM"` and `"WAVE_PROP"` both have big stencils, I think. I think that `CONSTANT` extrapolation is not very smart about what it does beyond the first layer of ghost cells --- I think it really just extends from the first layer inside the domain. OTOH, homogeneous Neumann will mirror from inside the domain across the interface.

**Comment by abarret** [comment]
I have two test functions, one that doesn't strictly satisfy zero Neumann conditions, e.g. sine along the boundary, and one that does, e.g. cosine on the boundary.

For the function that does satisfy zero Neumann conditions, the errors are the same for all convective operators.

For the function that does _not_ satisfy zero Neumann conditions, the errors are different for `PPM` and `WAVE_PROP`.

**Comment by abarret** [comment]
I think `CartExtrapPhysBdryOp` + `CONSTANT` does a constant extrapolation from the cell center nearest the boundary, i.e. all ghost cells in a "row" or "column" will have the same value as the cell interior nearest the boundary.

The `AdvDiffPhysicalBoundaryUtilities` actually uses a linear interpolant to enforce Neumann conditions by using a "mirrored" index across the boundary. It's not a surprise that for larger ghost cell widths, we get different results.

**Comment by boyceg** [comment]
Yeah, that is what my comment above was meant to convey.

So I guess a question is whether it would be better to use a homogeneous Neumann condition at outflow instead of extrapolation.

What is accuracy like with higher-order extrapolation?

**Comment by abarret** [comment]
When looking at the accuracy of the convective operators `QUADRATIC` is pretty much the same as using Neumann boundary conditions. But this is without timestepping, just looking at the error the for operator alone.

For `QUADRATIC`:
```
Error using: CENTERED:
  L1-norm :0.00775729
  L2-norm :0.012055
  max-norm:0.153007
Error using: CUI:
  L1-norm :0.0158121
  L2-norm :0.0505137
  max-norm:0.61586
Error using: PPM:
  L1-norm :0.00160593
  L2-norm :0.00781859
  max-norm:0.118163
Error using: WAVE_PROP:
  L1-norm :0.00156932
  L2-norm :0.00818591
  max-norm:0.127983
```

For Neumann boundaries:
```
Error using: CENTERED:
  L1-norm :0.00775396
  L2-norm :0.0120602
  max-norm:0.153007
Error using: CUI:
  L1-norm :0.0159243
  L2-norm :0.0506941
  max-norm:0.61586
Error using: PPM:
  L1-norm :0.00155912
  L2-norm :0.0078097
  max-norm:0.118163
Error using: WAVE_PROP:
  L1-norm :0.00152674
  L2-norm :0.0081762
  max-norm:0.127983
```

**Comment by abarret** [comment]
Linear on the other hand is much worse, at least for `PPM` and `WAVE_PROP`

**Comment by abarret** [comment]
All of the error for `QUADRATIC` and Neumann boundaries seem to be located at the inflow boundaries. Below is a picture for error of the `WAVE_PROP` operator with a constant velocity diagonally upwards with a sinusoidal concentration.

error_wave_prop

**Comment by boyceg** [comment]
At inflow boundaries you should actually provide a boundary condition shouldn't you?

**Comment by abarret** [comment]
> At inflow boundaries you should actually provide a boundary condition shouldn't you?

Yes and that is what I'm doing.

**Comment by boyceg** [comment]
Aha -- I misunderstood what you were saying about the test.

**Comment by abarret** [comment]
I forced pushed an update to the tests. Unless you have something else you want added, I suggest we merge this and if we want to change how boundary conditions are treated, we can do that in a different branch.

**Comment by boyceg** [comment]
OK, then this is good to go once Jenkins is happy and someone approves. :-)

**Comment by amneetb** [comment]
Does CUI look correct for inflow/outflow conditions? @ramakrishnan is using that for testing his turbulence code (turbulent flow in a channel)

**Comment by abarret** [comment]
> Does CUI look correct for inflow/outflow conditions? @ramakrishnan is using that for testing his turbulence code (turbulent flow in a channel)

`CUI` seems to be having different problems. Below is a some plots for the test I've been running. It computes the operator with a velocity up and to the right. Left is the original data, middle is the convective operator output, right is the error. The output of the operator is shifted for some reason.

I have, however, tested it with `adv_diff/ex0` with no diffusion, and the result is still second order, so I'm not sure what's going on.
error_cui

**Comment by boyceg** [comment]
> > Does CUI look correct for inflow/outflow conditions? @ramakrishnan is using that for testing his turbulence code (turbulent flow in a channel)
> 
> `CUI` seems to be having different problems. Below is a some plots for the test I've been running. It computes the operator with a velocity up and to the right. Left is the original data, middle is the convective operator output, right is the error. The output of the operator is shifted for some reason.
> 
> I have, however, tested it with `adv_diff/ex0` with no diffusion, and the result is still second order, so I'm not sure what's going on.
> error_cui
> 
> Edit: The same kind of thing happens in 3D so...? I don't know.

Is this for one patch or multiple patches?

**Comment by nishantnangia** [comment]
I wrote the AdvDiffCUIConvectiveOperator class, right? Off the top of my head, I'm not sure what could be going on, but happy to take a look @amneetb, if it's mission critical.

**Comment by abarret** [comment]
This is for one patch. Although it sure looks like multiple patches. All I can think of is that there's an off by one index issue somewhere in the cui code causing things to get shifted, but I couldn't find anything.

**Comment by amneetb** [comment]
> I wrote the AdvDiffCUIConvectiveOperator class, right? Off the top of my head, I'm not sure what could be going on, but happy to take a look @amneetb, if it's mission critical.

So far we are using PPM for advecting level set as it is not a bounded field. We have tried CUI on several WSI problems and the results with CUI looked quite reasonable and matched well with PPM. But if there is a bug, let's fix it now, because @Raamkrishnan has based his `AdvDiffConservativeCUIConvectiveOperator` on `AdvDiffCUIConvectiveOperator`.

**Comment by amneetb** [comment]
> > Does CUI look correct for inflow/outflow conditions? @ramakrishnan is using that for testing his turbulence code (turbulent flow in a channel)
> 
> `CUI` seems to be having different problems. Below is a some plots for the test I've been running. It computes the operator with a velocity up and to the right.

Can you point me to the test? Perhaps it the time level at which we are applying the operator that is different than PPM??

 Left is the original data, middle is the convective operator output, right is the error. The output of the operator is shifted for some reason.
> 
> I have, however, tested it with `adv_diff/ex0` with no diffusion, and the result is still second order, so I'm not sure what's going on.
> error_cui
> 
> Edit: The same kind of thing happens in 3D so...? I don't know.



> > Does CUI look correct for inflow/outflow conditions? @ramakrishnan is using that for testing his turbulence code (turbulent flow in a channel)
> 
> `CUI` seems to be having different problems. Below is a some plots for the test I've been running. It computes the operator with a velocity up and to the right. Left is the original data, middle is the convective operator output, right is the error. The output of the operator is shifted for some reason.
> 
> I have, however, tested it with `adv_diff/ex0` with no diffusion, and the result is still second order, so I'm not sure what's going on.
> error_cui
> 
> Edit: The same kind of thing happens in 3D so...? I don't know.

**Comment by abarret** [comment]
> > > Does CUI look correct for inflow/outflow conditions? @ramakrishnan is using that for testing his turbulence code (turbulent flow in a channel)
> > 
> > 
> > `CUI` seems to be having different problems. Below is a some plots for the test I've been running. It computes the operator with a velocity up and to the right.
> 
> Can you point me to the test? Perhaps it the time level at which we are applying the operator that is different than PPM??

It's on this branch, the test `tests/adv_diff/adv_diff_convec_opers_2d`. The visualization is disabled for the test, but you can enable it in the .cpp file by uncommenting the line
```
//#define OUTPUT_VIZ_FILES
```
The `CUI` operator is the second value outputted. Note this test has _no_ time dependence. It strictly computes the operator from a prescribed function and velocity field.

**Comment by boyceg** [comment]
Are we trying to fix these issues in this PR or just add in this "feature"? :-)

**Comment by abarret** [comment]
Let's merge this PR and I'll open an issue for the `CUI` operator. @drwells, when you get a chance can you review this PR?

**Comment by drwells** [comment]
Sure. I don't know this part of the library very well so, since everyone is happy, I'll just merge as-is.

**Pull request merged**
