### PR TITLE
Namupatel/constraint ib restart bug fix

### PR DESCRIPTION
**Pull request by namupatel**
Fixed restart bug for ConstraintIBMethod and updated examples

### CODE REVIEW

**Comment by boyceg** [comment]
Woah please wait for someone to review before merging...

**Comment by boyceg** [comment]
This PR included a spurious commit.

**Comment by namupatel** [comment]
I believe that when I squashed my commits, somehow your name got tacked
onto my commit. Apologies.

**Comment by boyceg** [comment]
The convective boundary stabilization stuff belongs in a different branch. Please be careful when squashing, and ask for someone to review a PR before merging.

**Comment by namupatel** [comment]
Will do in the future. I don't want to mess with master to fix this. Can
you please do take care of this. Thanks and my apologies again.

**Pull request merged**
