### PR TITLE
Use Eigen, not LAPACK, for eigenvalues.

### PR DESCRIPTION
**Pull request by drwells**
First part of #1215 - we can replace everything we use LAPACK for with Eigen, our preferred dense linear algebra library.

One odd thing I noticed is that the mobility matrix isn't actually symmetric, though it is pretty close (off-diagonals are orders of magnitude smaller than diagonal entries). We could definitely switch to an SVD solver here instead, but I only changed the minimum necessary to get things working with Eigen.

@amneetb no rush, but I think you should review this one. We do have some tests that use the SVD-based solver and they pass (and the computed torques and drags are the same to 8+ digits).

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
@amneetb, are there any approximations that are used here that would impact the symmetry of the mobility matrix?

**Comment by drwells** [comment]
I checked a couple of the mobility matrices and if the main diagonal entries are `O(10^2)` then the values of `A - A^T` are `O(10^-12)`: its just due to roundoff.

Only the smaller (6x6, not circa 2000x2000) mobility matrices have this problem. I don't think its worth worrying about: I'm not an expert but all these matrices are diagonally dominant anyway so these errors are irrelevant.

**Comment by amneetb** [comment]
> Only the smaller (6x6, not circa 2000x2000) mobility matrices have this problem. I don't think its worth worrying about: I'm not an expert but all these matrices are diagonally dominant anyway so these errors are irrelevant.

The 6x6 matrix would be the body mobility matrix; see Eqn. 12 of this paper.
https://msp.org/camcos/2016/11-2/camcos-v11-n2-p04-s.pdf

It is constructed from the actual symmetric mobility matrix by multiplying by a geometric matrix K (which is basically a rigid body operator that maps translation (U) and rotation (W) velocity of the center of mass to the velocity of a marker point, i.e.,  K: U x W -> U + Wx (X - X_com).  

So it is expected that it won't be perfectly symmetric due to various floating point operations resulting from triple matrix multiplication.

**Comment by amneetb** [comment]
@drwells : Thanks for modernizing the CIB matrix solvers.

**Comment by drwells** [comment]
@amneetb I think your previous messages imply that you approve, but just to be sure - if you are OK with this change then can you hit the `approve` button on GitHub? You know this area best so I want your explicit sign-off before merging.

**Comment by amneetb** [comment]
@drwells : Can you verify the output of CIB/examples/ex1 with the new branch? This examples tests both kinds of mobility matrices (fluid and body). This is what I get as an output with the master branch:

```
amneetb@Amneets-MacBook-Pro:~/Softwares/IBAMR-Git/objs-dbg/examples/CIB/ex1$ mpiexec -np 4 ./main3d input3d  -SP_ksp_monitor_true_residual
IBStandardInitializer:  Reading from input files.
  base filename: shell_3d_out
  assigned to level 0 of the Cartesian grid patch hierarchy
  NOTE: UNIFORM spring stiffnesses are being employed for the structure named shell_3d_out

  base filename: shell_3d_in
  assigned to level 0 of the Cartesian grid patch hierarchy
  NOTE: UNIFORM spring stiffnesses are being employed for the structure named shell_3d_in



Writing visualization files...


+++++++++++++++++++++++++++++++++++++++++++++++++++
At beginning of timestep # 0
Simulation time is 0
Advancing hierarchy by timestep size dt = 1e-16
  Residual norms for SP_ solve.
  0 KSP unpreconditioned resid norm 5.822462238929e+04 true resid norm 5.822462238929e+04 ||r(i)||/||b|| 1.000000000000e+00
  1 KSP unpreconditioned resid norm 1.649684514156e+02 true resid norm 1.649684514156e+02 ||r(i)||/||b|| 2.833310799555e-03
  2 KSP unpreconditioned resid norm 1.159036356578e+02 true resid norm 1.159036356578e+02 ||r(i)||/||b|| 1.990629237281e-03
  3 KSP unpreconditioned resid norm 8.821981410383e+01 true resid norm 8.821981410383e+01 ||r(i)||/||b|| 1.515163353297e-03
  4 KSP unpreconditioned resid norm 8.768545039661e+01 true resid norm 8.768545039661e+01 ||r(i)||/||b|| 1.505985729033e-03
  5 KSP unpreconditioned resid norm 5.771207837501e+01 true resid norm 5.771207837501e+01 ||r(i)||/||b|| 9.911971260052e-04
  6 KSP unpreconditioned resid norm 2.183362951602e+01 true resid norm 2.183362951602e+01 ||r(i)||/||b|| 3.749896284434e-04
  7 KSP unpreconditioned resid norm 6.559294841414e+00 true resid norm 6.559294841414e+00 ||r(i)||/||b|| 1.126550001056e-04
  8 KSP unpreconditioned resid norm 2.433328638179e+00 true resid norm 2.433328638179e+00 ||r(i)||/||b|| 4.179208964052e-05
  9 KSP unpreconditioned resid norm 1.005474099671e+00 true resid norm 1.005474099671e+00 ||r(i)||/||b|| 1.726888141838e-05
 10 KSP unpreconditioned resid norm 6.968688658171e-01 true resid norm 6.968688658171e-01 ||r(i)||/||b|| 1.196862834348e-05
 11 KSP unpreconditioned resid norm 6.943868202933e-01 true resid norm 6.943868202933e-01 ||r(i)||/||b|| 1.192599954793e-05
 12 KSP unpreconditioned resid norm 5.315943211483e-01 true resid norm 5.315943211483e-01 ||r(i)||/||b|| 9.130060433780e-06
 13 KSP unpreconditioned resid norm 4.995045082816e-01 true resid norm 4.995045082816e-01 ||r(i)||/||b|| 8.578922246020e-06
 14 KSP unpreconditioned resid norm 4.972063308865e-01 true resid norm 4.972063308866e-01 ||r(i)||/||b|| 8.539451360667e-06
 15 KSP unpreconditioned resid norm 4.750302254996e-01 true resid norm 4.750302254995e-01 ||r(i)||/||b|| 8.158579755544e-06
 16 KSP unpreconditioned resid norm 3.750938640620e-01 true resid norm 3.750938640619e-01 ||r(i)||/||b|| 6.442186289402e-06
 17 KSP unpreconditioned resid norm 2.534080215907e-01 true resid norm 2.534080215907e-01 ||r(i)||/||b|| 4.352248433599e-06
 18 KSP unpreconditioned resid norm 1.429104269498e-01 true resid norm 1.429104269498e-01 ||r(i)||/||b|| 2.454467218255e-06
 19 KSP unpreconditioned resid norm 8.376510152873e-02 true resid norm 8.376510152871e-02 ||r(i)||/||b|| 1.438654268441e-06
 20 KSP unpreconditioned resid norm 3.943449405283e-02 true resid norm 3.943449405285e-02 ||r(i)||/||b|| 6.772820919162e-07
 21 KSP unpreconditioned resid norm 1.424058624767e-02 true resid norm 1.424058624778e-02 ||r(i)||/||b|| 2.445801391818e-07
 22 KSP unpreconditioned resid norm 5.548374391915e-03 true resid norm 5.548374391933e-03 ||r(i)||/||b|| 9.529257836721e-08
 23 KSP unpreconditioned resid norm 2.892953914001e-03 true resid norm 2.892953913830e-03 ||r(i)||/||b|| 4.968609146981e-08
 24 KSP unpreconditioned resid norm 1.277730353996e-03 true resid norm 1.277730353953e-03 ||r(i)||/||b|| 2.194484569449e-08
 25 KSP unpreconditioned resid norm 5.542328586054e-04 true resid norm 5.542328586978e-04 ||r(i)||/||b|| 9.518874248632e-09
 26 KSP unpreconditioned resid norm 2.609064522597e-04 true resid norm 2.609064523128e-04 ||r(i)||/||b|| 4.481032965201e-09
 27 KSP unpreconditioned resid norm 1.166757527165e-04 true resid norm 1.166757526516e-04 ||r(i)||/||b|| 2.003890242026e-09
 28 KSP unpreconditioned resid norm 4.891350434380e-05 true resid norm 4.891350438155e-05 ||r(i)||/||b|| 8.400828098895e-10
 29 KSP unpreconditioned resid norm 1.700247811008e-05 true resid norm 1.700247823671e-05 ||r(i)||/||b|| 2.920152598506e-10
 30 KSP unpreconditioned resid norm 7.268299836026e-06 true resid norm 7.268299810280e-06 ||r(i)||/||b|| 1.248320643745e-10
 31 KSP unpreconditioned resid norm 3.390984624661e-06 true resid norm 3.390984609424e-06 ||r(i)||/||b|| 5.823970118263e-11

+++++++++++++++++++++++++++++++++++++++++++++++++++
Interpolating velocity on structure at time  5e-17....



Net rigid force and torque on structure 0 is : 
     100.916
     1351.74
 0.000916801
-2.24168e-09
     58206.1
-1.12334e-09



Net rigid force and torque on structure 1 is : 
    -116.762
     -201.82
 -0.00128574
 1.46265e-09
    -1393.33
-4.97728e-09



Rigid body velocity of structure 0 is : 
           1
           2
 6.28892e-09
  3.4987e-11
           5
-6.30934e-11



Rigid body velocity of structure 1 is : 
 3.20859e-06
-2.26192e-06
           0
 1.09477e-10
 6.73728e-06
           0


At end       of timestep # 0
Simulation time is 1e-16
+++++++++++++++++++++++++++++++++++++++++++++++++++


Writing visualization files...


Writing restart files...


Writing timer data...

IBStandardInitializer:  Deallocating initialization data.
IBStandardInitializer:  Deallocating initialization data.

```

**Comment by drwells** [comment]
Can do!

**Comment by drwells** [comment]
The differences are quite small. Here `out-amneet` is what you have, `out-master` is what I get by running the same thing on my machine on `master`, and `out-feature` is from this branch:
```
[drwells@archway ex1]$ numdiff -r 1e-12 -a 1e-12 out-feature out-master
----------------
##29      #:6   <== 1.005474099670e+00
##29      #:6   ==> 1.005474099675e+00
@ Absolute error = 5.0000000000e-12, Relative error = 4.9727785148e-12
##29      #:10  <== 1.005474099670e+00
##29      #:10  ==> 1.005474099674e+00
@ Absolute error = 4.0000000000e-12, Relative error = 3.9782228118e-12
----------------
##64      #:1   <== -1.12732e-09
##64      #:1   ==> -1.12414e-09
@ Absolute error = 3.1800000000e-12, Relative error = 2.8288291494e-3
----------------
##74      #:1   <== -4.9761e-09
##74      #:1   ==> -4.9773e-09
@ Absolute error = 1.2000000000e-12, Relative error = 2.4115270995e-4

+++  File "out-feature" differs from file "out-master"
[drwells@archway ex1]$ numdiff -r 1e-12 -a 1e-12 out-feature out-amneet
----------------
##22      #:6   <== 1.159036356576e+02
##22      #:6   ==> 1.159036356578e+02
@ Absolute error = 2.0000000000e-10, Relative error = 1.7255714099e-12
##22      #:10  <== 1.159036356576e+02
##22      #:10  ==> 1.159036356578e+02
@ Absolute error = 2.0000000000e-10, Relative error = 1.7255714099e-12
----------------
##62      #:1   <== -2.23883e-09
##62      #:1   ==> -2.24168e-09
@ Absolute error = 2.8500000000e-12, Relative error = 1.2729863366e-3
----------------
##64      #:1   <== -1.12732e-09
##64      #:1   ==> -1.12334e-09
@ Absolute error = 3.9800000000e-12, Relative error = 3.5430056795e-3
----------------
##72      #:1   <== 1.46483e-09
##72      #:1   ==> 1.46265e-09
@ Absolute error = 2.1800000000e-12, Relative error = 1.4904454244e-3
----------------
##74      #:1   <== -4.9761e-09
##74      #:1   ==> -4.97728e-09
@ Absolute error = 1.1800000000e-12, Relative error = 2.3713349812e-4

+++  File "out-feature" differs from file "out-amneet"
```
so the errors are within a reasonable numerical tolerance (and changing machines has about as much of a change as changing branches).

**Review by amneetb — APPROVED** [review]

**Pull request merged**
