### PR TITLE
Remove the dX system.

### LINKED ISSUE #1071: Remove dX system?
A drawback to using `ReplicatedMesh` is that every single dof is allocated on every single processor - i.e., every time we add a system to the mesh we have to allocate an amount of memory proportional to the number of processors.

We only ever use this system to calculate the vector indicating the displacement of the mesh - i.e., all the information we need in this system is already available in `X`. Similarly, if for some reason someone wants to plot this, we can use this same information to recover this vector.

I think we are at the point where this is necessary to consider since the heart mesh is big enough that we are having trouble allocating everything we need - the more we can cut out of the mesh, the better.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #1071 - I'm testing it now to see how much of a difference this makes.

Still WIP since this causes tests that print out dof counts to (as expected) print about 10% fewer dofs. I should also take a closer look at the meter code to figure out if I broke anything since that area is under-tested.

### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
This lowers memory usage, with 12 processors on my workstation, from about 36.3 GB to 35.1 GB: not a ton but every little bit helps.

**Comment by boyceg** [comment]
Seems like a good idea. As long as initial and current coordinates are available, we can omit "dX". We need to make sure that both are stored in the viz files.

**Comment by drwells** [comment]
Would initial coordinates ever be different from the coordinates at timestep 0? Those are definitely stored.

**Comment by boyceg** [comment]
I am not sure if this is answering your question, but initial coordinates can be different from mesh coordinates.

**Comment by boyceg** [comment]
Also, AFAIK, it is not easy to access solution values at different time steps in VisIt --- so using the initial value of the current position to compute displacements could be tricky.

**Comment by drwells** [comment]
I don't know of any way to save a libMesh vector with a visualization format outside of what they provide for system solutions so I don't think that we have a way to resolve this problem - i.e., there is no good way to visualize this data without actually allocating it. Hence lets close this for now.

**Pull request closed without merging**
