### PR TITLE
Backport a boost fix.

### PR DESCRIPTION
**Pull request by drwells**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

There are a few failing tests on longleaf but they are unrelated to this PR and are generally harmless (e.g., the lagrangian point error has a relative error of about 2e-6 and some L2 error norms are slightly lower).

### CODE REVIEW

**Review by boyceg — APPROVED** [review]

**Comment by N-Gh** [comment]
Hello,

Could you please unsubscribe me from this thread?

Thanks,
Najmeh

**Comment by drwells** [comment]
@N-Gh I think you need to unstar this repository or change your GitHub settings to unsubscribe - it's not something Boyce or I can do. Do you see how to do that?

**Comment by N-Gh** [comment]
Hi David,
Thanks for your guidance!  I did unstar it,  but I am still receiving the
emails.
Could you please help me with this?
Thanks!
Najmeh

**Comment by drwells** [comment]
@N-Gh Are you sure you unstarred this repository? I see it on your list at

https://github.com/N-Gh?tab=stars

**Comment by N-Gh** [comment]
Thanks, David! I did unstar and deactivated notifications. It seems that it
was fixed.

**Pull request merged**
