### PR TITLE
Fix staggered stokes operator application at physical boundaries.

### PR DESCRIPTION
**Pull request by abarret**
`StaggeredStokesOperator` should not require a boundary condition helper if there are no boundaries (e.g. periodic boundary conditions).

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Review by boyceg — APPROVED** [review]
Looks good. Is there a test?

**Comment by abarret** [comment]
I've added a test that checks whether we can apply `StaggeredStokesOperator` to known quantities.

**Comment by drwells** [comment]
Looks good (and I see the test passing in the CI).

Could you also set up the test to be compiled with autotools?

**Comment by abarret** [comment]
Ugh, I always forget about autotools. We should just get rid of it :D. It has been fixed

**Comment by drwells** [comment]
cdash timed out:

    Error message was: Failed to connect to open.cdash.org port 80: Connection timed out
[1121](https://github.com/IBAMR/IBAMR/runs/5401144491?check_suite_focus=true#step:9:1121)

but the test compiles cleanly with autotools and cmake.

I'd also like to get rid of autotools but most projects are still using it.

**Review by drwells — APPROVED** [review]

**Pull request merged**
