### PR TITLE
Remove CIBFEMethod

### LINKED ISSUE #721: CIBFEMethod doesn't work
I tried to write a test for CIBFEMethod based on `examples/CIBFE/ex0/example.cpp` but then realized that this class has some serious problems: there will always be a segmentation fault in the constructor since it tries to add a system to the `EquationSystems` object which is not set up until we actually call `initializeFEEquationSystems`.

I suspect that this is already known and is why we did #193. We should either fix this class or remove it.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #721. I'll put up a branch that reverts this commit once this is merged so that its clear what the state of the implementation is.

### CODE REVIEW

**Comment by drwells** [comment]
It looks like our copyright fix made this totally out of date. @amneetb are you okay with deleting this and then putting the code on a new branch on GitHub? If so I'll go ahead and do it :)

**Comment by amneetb** [comment]
Yes, go ahead. You can also put `CIBStochasticMethod` (#523) there.

**Comment by drwells** [comment]
Sounds good. I fixed the merge conflicts. Once this is merged I will put up a new branch `add-CIBFEMethod` that reverts the relevant commit.

**Comment by drwells** [comment]
This conflicts with #772 - lets merge that first.

**Comment by drwells** [comment]
The branch is
https://github.com/IBAMR/IBAMR/tree/add-CIBFEMethod

which just reverts this PR.

**Pull request merged**
