### PR TITLE
IBFE ex7 tiny fix

### PR DESCRIPTION
**Pull request by sach1**
Removed code that was previously enclosed in {{ #if 0, #endif }}

Example now compiles & runs successfully.

### CODE REVIEW

**Comment by sach1** [comment]
Also want to point out that the PK1 stress function arguments keep switching between commits for all the IBFE examples (even in prior versions of main.cpp where tests were not yet set up)

It changes between this

```cpp
void
upper_PK1_stress_function(
    TensorValue<double>& PP,
    const TensorValue<double>& FF,
    const libMesh::Point& /*X*/,
    const libMesh::Point& s,
    Elem* const /*elem*/,
    const vector<const vector<double>*>& /*var_data*/,
    const vector<const vector<VectorValue<double> >*>& /*grad_var_data*/,
    double /*time*/,
    void* /*ctx*/)
```

and

```cpp
void
upper_PK1_stress_function(
    TensorValue<double>& PP,
    const TensorValue<double>& FF,
    const libMesh::Point& /*X*/,
    const libMesh::Point& s,
    Elem* const /*elem*/,
    const vector<NumericVector<double>*>& /*system_data*/,
    double /*time*/,
    void* /*ctx*/)
```
not sure if this is intentional...

**Comment by boyceg** [comment]
Yes there was a change, but the arguments should not be jumping back-and-forth. Let me know if this is not the case.

The new interface (with var_data and grad_var_data) is meant to make it easier to use additional field variables in evaluating these kinds of functions, by pre-evaluating the function value or gradient of the extra variable at the location where the stress is being evaluated.

The old interface (with system_data) just passed the full NumericVector to the stress function and left it up to the stress function to evaluate the field variable at the right place.

**Comment by sach1** [comment]
Oh, I understand now. Thanks for the detailed explanation.

**Comment by boyceg** [comment]
Jenkins check this please.

**Comment by boyceg** [comment]
ok to test

**Comment by boyceg** [comment]
Jenkins check this please.

**Comment by boyceg** [comment]
Hmmmm, it looks like the compiler is just crashing on the new VM...

**Comment by boyceg** [comment]
retest this please

**Comment by boyceg** [comment]
Hmmm, Jenkins is having trouble with this branch. I am going to go ahead and merge since it only touches the example code.

**Pull request merged**
