### PR TITLE
Disambiguate SAMRAI::hier::Index and Eigen::Index.

### PR DESCRIPTION
**Pull request by drwells**
I cannot compile the examples without the namespace qualification.

### CODE REVIEW

**Comment by boyceg** [comment]
I think you should be able to switch from SAMRAI::hier::Index to the slightly shorter hier::Index and have everything work. Can you give it a shot?

**Comment by drwells** [comment]
Yes, that works.

**Comment by drwells** [comment]
I pushed an ammended commit that just writes `hier::Index`.

**Comment by boyceg** [comment]
Are there any unqualified uses of Index left in the examples? If so, should we namespace all of them?

**Comment by boyceg** [comment]
> On Jul 19, 2018, at 11:50 AM, David Wells <notifications@github.com> wrote:
> 
> There were two more unqualified uses of Index (I did not notice them before because GCC was happy with their namespaces). I prepended hier:: to those so now all of them in examples/ are qualified.
> 
Great; if you haven't already do so, can you also check in ibtk/examples? I am always surprised about what will compile and what won't.

**Comment by drwells** [comment]
I found a few there as well; they are now qualified!

**Comment by boyceg** [comment]
👍

**Pull request merged**
