### PR TITLE
Fix CIBStaggeredStokesOperator

### PR DESCRIPTION
**Pull request by amneetb**

### CODE REVIEW

**Comment by amneetb** [comment]
Can you please check if `CIB/ex4` runs in parallel? 

`$mpiexec -np 8 ./main3d input3d.sphere -sp_ksp_monitor_true_residual`

For some reason I cannot get 3d solvers working in parallel. The 2d cases like `ex2` work fine in parallel. It could be something related to my build. Please confirm.

**Comment by amneetb** [comment]
All of the CIB examples worked in parallel before.

**Comment by amneetb** [comment]
Checked it on two linux systems with mpich-3.3 and openmpi 1.17, things are working in parallel. Checked on two OS X Catalina with mpich 3.3 self built and home-brew, it is not converging in 3d parallel. 

I hate updating operating systems...

**Comment by boyceg** [comment]
> Checked it on two linux systems with mpich-3.3 and openmpi 1.17, things are working in parallel. Checked on two OS X Catalina with mpich 3.3 self built and home-brew, it is not converging in 3d parallel.

Ugh. We just ordered a Mac Mini to put in @drwells' office to run the testsuite.

**Comment by amneetb** [comment]
Just built MPICH 3.2. Even PETSc errors out on `make check`. IBAMR also failed. Trying OpenMPI now :-(

**Comment by boyceg** [comment]
Hmm, now I really don't want to update to Catalina!

**Comment by amneetb** [comment]
> Hmm, now I really don't want to update to Catalina!

That would keep you sane!

**Comment by amneetb** [comment]
Can @drwells or @boyceg merge this PR?

**Comment by boyceg** [comment]
Are you not able to merge? They are approved.

**Comment by drwells** [comment]
@amneetb are you unable to merge approved PRs? If so we have misconfigured GitHub.

**Comment by nishantnangia** [comment]
Coincidentally, I also recently upgraded to Catalina and I am also unable to get `CIB/ex1` to converge in parallel.

Running:
`mpiexec -np 2 ./main3d input3d -sp_ksp_monitor_true_residual -sp_ksp_converged_reason`
yields
`Linear SP_ solve did not converge due to DIVERGED_NANORINF iterations 0`

while running with a single processor yield nice, convergent behavior. I am using MPICH version 3.2.1 built with Homebrew.

**Comment by drwells** [comment]
This could be related to #906 - would you be willing to take a look? It might be worthwhile trying to hardcode a few of the unset booleans just to see if it makes a difference.

**Comment by nishantnangia** [comment]
Sure I can take a look. I'll report back if anything I try makes a
difference or not.

**Pull request merged**
