### PR TITLE
increment version to 0.13-pre

### PR DESCRIPTION
**Pull request by drwells**
More release stuff. Note that this is on `master`.

### CODE REVIEW

**Comment by amneetb** [comment]
Would this release include #1505?

**Comment by boyceg** [comment]
> Would this release include #1505 <https://github.com/IBAMR/IBAMR/pull/1505>?
> 
I think I am the main one who has done much review on this so far, and I won’t be able to do any more until next week. (Ideally David and/or Aaron also would take a look before it is merged.)

**Comment by drwells** [comment]
No, none of that has been merged. The 0.12 branch already exists (and we have a release candidate) - those new things will need to go in the next release in June.

**Comment by drwells** [comment]
More precisely - the 0.13 release (in June 2023) will include those changes. 0.12, which is mostly done (released tonight) will not.

**Review by abarret — APPROVED** [review]

**Pull request merged**
