### PR TITLE
use tsl::robin_map instead of std::unordered_map

### PR DESCRIPTION
**Pull request by boyceg**
In profiling, I am seeing that the DOF index cache is relatively expensive. However, most of those lookups are related to getting data from a map.

This uses [tsl::robin_map](https://github.com/Tessil/robin-map) in place of `std::unordered_map` in an attempt to speed things up.

At least on my Mac, there is very little performance difference.

### CODE REVIEW

**Comment by drwells** [comment]
I'll take a look.

**Comment by boyceg** [comment]
On Mac, I think that `std::unordered_map` is from libc++. I have not made any comparisons for GNU libstdc++.

I don't know if look-ups for other caching objects are worth optimizing, but we could try to make a hash function for the `std::tuple` keys.

**Comment by drwells** [comment]
I am yet to see any of the other lookups show up in profiling, but adding a hash would be pretty easy: the keys are, currently, just three integers. In particular, since each integer is bounded by something small (e.g., we only use up to order 43 quadrature rules) we could probably do this by bit shifting their values onto a 64 bit key with something like `union {std::size_t, short int[4]}`.

There has to be a better way to cache these values that doesn't involve a hash table: there are always N elements contiguously. One possibility would be to add even more band-aids and just start indexing libMesh cells with our own ids so we can look stuff up directly in a contiguous buffer.

**Comment by boyceg** [comment]
For the other caching data structures we could just use `boost::multi_array`.

**Comment by drwells** [comment]
Using a non-sparse data structure could result in some very large arrays: e.g., if we have 100 valid element types, 50 valid orders, and 10 valid quadrature rule types we are now allocating room for 50,000 pointers when we only need a few dozen or so :)

**Comment by boyceg** [comment]
Oh yeah, I was thinking there were fewer element types at play.

I guess we should just leave these alone unless they show up in profiling.

**Comment by drwells** [comment]
I think I know another way to improve this. In every case that we look up data with `SystemDofMapCache` in `FEDataManager` we always have `e_idx` around: i.e., we can always look up any element dof info by indexing an array instead of traversing an array. We will have to add some more assertions to guarantee that we are always on the correct patch but that should be straightforward.

**Comment by boyceg** [comment]
Are `e_idx` ranges continuous? If so then it would be better to just use an array.

**Comment by boyceg** [comment]
I can take a look at this while you work on partitioning.

**Comment by boyceg** [comment]
But those ranges change dynamically. (Would need to invalidate the caches, which we can do when resetting the active element lists.)

**Comment by drwells** [comment]
Do they change more frequently than the interval at which we regrid?

**Comment by boyceg** [comment]
Looking more carefully at the profiling data, I think that the expensive part of the DOF cache lookup is actually coping the data out of the cache, not looking it up. I am going to experiment with just returning a pointer to the data and see if it makes a difference.

**Pull request closed without merging**
