### PR TITLE
Remove some unused includes.

### PR DESCRIPTION
**Pull request by drwells**
These are used by the base class only. I think they were added by iwyu.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Review by boyceg — APPROVED** [review]
Is it worth applying IWYU in an effort to reduce compilation time? (https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md)

**Comment by drwells** [comment]
Theoretically yes, but in practice running IWYU was such a painful experience (see #917 and #920) that I would really rather not bother with it ever again.

**Comment by boyceg** [comment]
I guess it might be worth trying again with CMake? (https://github.com/include-what-you-use/include-what-you-use#using-with-cmake)

**Comment by drwells** [comment]
Its worth a try, but I don't think that will fix the more fundamental problems of IWYU (like including private PETSc headers, internal compiler headers, etc). Trying to minimize the header count just does weird things.

**Pull request merged**
