### PR TITLE
Fixing restart for IBLevelSet/ex0

### PR DESCRIPTION
**Pull request by amneetb**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by amneetb** [comment]
#824

**Comment by boyceg** [comment]
If `IBFEMethod` is only used internally in `IBLevelSetMethod`, could it be responsible for creating it as needed?

**Comment by amneetb** [comment]
I think so. The design is such that the application can control when to abort IBFEMethod amidst a simulation, or even not use it at all (for example when FEDistanceEvaluator is not used for calculating level set). The possible number of combinations are many, so I left it to the application.

**Comment by boyceg** [comment]
It seems like the application code has to do things differently for de novo vs. restarted runs. Typically, restartable objects allow the application code to set up everything in the same way whether things are from restart or not, and the implementations sorts out the details internally.

Can `IBLevelSetMethod` can be set up to "do the right thing" in either case, to simplify the application code?

**Comment by drwells** [comment]
@amneetb I'd like to get this into 0.7 but its missing a lot of checkmarks. What do you plan on doing?

**Comment by amneetb** [comment]
I think this only changing an example, and no other file in the library, so it should be fine to merge. The CI says that all checks have passed. Most of the checkboxes don't apply to this commit, I think. 

Regarding "Does the test suite pass?". Isn't this be checked by the CI system?  Github says "All checks have passed", so I presume I can checkmark the first box?

**Comment by drwells** [comment]
The CI is not yet set up to run the test suite, unfortunately.

Would you please add a changelog entry? Once that's done lets merge.

**Comment by amneetb** [comment]
@drwells:  I've added it.

**Pull request merged**
