### PR TITLE
swapping boost detection order

### PR DESCRIPTION
**Pull request by boyceg**
We need to detect Boost before libMesh in configure.

### CODE REVIEW

**Comment by boyceg** [comment]
Jenkins test this again please.

**Comment by boyceg** [comment]
Jenkins retest this please

**Comment by boyceg** [comment]
Jenkins retest this please

**Comment by cpuelz** [comment]
will this fix detection the detection of boost header files, like:

boost/move/unique_ptr.hpp?

**Comment by boyceg** [comment]
Still testing...

**Comment by boyceg** [comment]
Jenkins retest this please.

**Comment by boyceg** [comment]
Jenkins retest this please.

**Comment by boyceg** [comment]
Jenkins retest this please.

**Pull request merged**
