### PR TITLE
Rigid-body FSI using exactly constrained solvers -- refactored

### PR DESCRIPTION
**Pull request by amneetb**

### CODE REVIEW

**Comment by boyceg** [comment]
So this is obviously way too big of a change set to review exhaustively. :-) / :-(

Is it correct that there are no changes to existing IBAMR/IBTK classes in this PR, and that all of the library changes are in CIB-related stuff?

**Comment by amneetb** [comment]
On Wednesday, February 3, 2016, Boyce Griffith <notifications@github.com>
wrote:

> So this is obviously way too big of a change set to review exhaustively.
> :-) / :-(
>
> Is it correct that there are no changes to existing IBAMR/IBTK classes in
> this PR, and that all of the library changes are in CIB-related stuff?


Mostly. Some changes are in FeDataManager that splits interpolation
business into two parts: apply weighting and then do L2 projection. This is
done to make mobility matrix symmteric. I have still to merge master with
this branch.



>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBAMR/IBAMR/pull/55#issuecomment-179299912>.
>


-- 
--Amneet

**Comment by boyceg** [comment]
> On Feb 3, 2016, at 11:25 AM, Amneet Bhalla <notifications@github.com> wrote:
> 
> I have still to merge master with this branch.

Aha. Synching with master may make it easier to review changes.

**Comment by amneetb** [comment]
Ok, this is merged. I have also included the changes for applying physical boundary conditions in CIBStaggeredStokesOperator class.

**Comment by amneetb** [comment]
@boyceg and @adonev :Added flow past nozzle example to test the new implementation of applying boundary conditions. 

@fbusabiaga : Could you switch to this branch and try CIB/ex3 and possibly some simple test case of a body near (inhomogeneous) boundary whose analytical solution is known. This branch requires PETSc 3.6 (and libMesh 0.9.5 which you can disable).

**Comment by boyceg** [comment]
@amneetb Do we need MobilityFunctions.c? It does not have a header and is not properly namespaced. A quick check does not seem to show any parts of the library that use any of those functions. I would like to cut it from the library unless it is needed.

**Comment by amneetb** [comment]
I think so. It's referenced here:
https://github.com/IBAMR/IBAMR/blob/amneetb/RigidIBFE/src/IB/CIBMethod.cpp#L41-L64

This is taken verbatim from @adonev  site:
http://cims.nyu.edu/~donev/src/MobilityFunctions.c

**Comment by boyceg** [comment]
OK --- it needs to be cleaned up a bit before I will sign off on merging this branch.

There should be a properly namespaced header for any public functions, and function names should use established library conventions (e.g. this_is_a_static_function_name(), ThisIsNotAStaticFunctionName(), norIsThis()). Enums should be declared in an appropriate header (probably ibamr_enums.h). Private helper functions can be declared in a private namespace in the implementation file.

Once that is done, I will merge this thing.

**Comment by boyceg** [comment]
Also, we don't currently use enums anywhere else in the code for kernel function identifiers --- we should either use enums everywhere, or get rid of them here. My preference is not to use enums unless it affects performance, as it is not easily extensible in user code.

**Comment by amneetb** [comment]
Check now....

**Comment by boyceg** [comment]
Should CIBStandardInitializer be removed from the repo? It does not appear to be getting compiled at present, nor does it appear to compile without errors as currently implemented.

**Comment by amneetb** [comment]
Yep it should be removed, as it is application specific. I forgot to do
that myself. I think I just removed it from Makefile.am.

On Mon, Feb 29, 2016 at 2:15 PM, Boyce Griffith <notifications@github.com>
wrote:

> Should CIBStandardInitializer be removed from the repo? It does not appear
> to be getting compiled at present, nor does it appear to compile without
> errors as currently implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IBAMR/IBAMR/pull/55#issuecomment-190423036>.
>



-- 
--Amneet

**Comment by boyceg** [comment]
Geeze, who named an enum FILE?

**Comment by boyceg** [comment]
Fixing this in PR #68.

**Pull request merged**
