### PR TITLE
Remove CACHED assembly from IBFEMethod.

### PR DESCRIPTION
**Pull request by drwells**
It isn't possible for this to work correctly with constraints since we need ghost values to do the two-stage constraint resolution process implemented in e2e62c4d1bef6bfd817998ba87d0c37c913be1fd.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
Is this code path faster for problems without constraints?

**Comment by drwells** [comment]
Yes. Using `VecCache` for assembly is slower because it has to recompute the communication pattern and a lot of duplicated information ends up in the cache (e.g., if we sum to the same entry 10 times, we get 10 cache entries to communicate).

**Comment by boyceg** [comment]
Then should we keep it for cases where we can avoid using constraints?

**Comment by drwells** [comment]
Oh, I think I misunderstood your question. The faster code path is to always use ghosted assembly since it is much faster than relying on `VecCache`. Therefore there is no reason to use `CACHED` (it is slower and doesn't work in all cases).

**Comment by boyceg** [comment]
We should totally get rid of slower code that does not work. :-)

**Pull request merged**
