### PR TITLE
Use delete on private special member functions.

### PR DESCRIPTION
**Pull request by abarret**
This is a run of clang-tidy with modernize-use-equals-delete

### CODE REVIEW

**Comment by drwells** [comment]
I did not look very carefully but the lines changed count doesn't seem right: we should be able to delete all implementations but we are at +609 -609. Does this compile with the implementations?

**Comment by boyceg** [comment]
This is not worth doing by hand, but if you can cobble together a regex to wipe out the comments that are attached to these deleted functions, that would be awesome.

**Comment by drwells** [comment]
I'll see if I can throw something together.

**Comment by drwells** [comment]
Actually, it looks like a lot of these things were just never defined anyway (its not like we could use them so this never caused linking errors).

**Comment by drwells** [comment]
I could not find a single case of an implemented private copy constructor (or copy operator) so I think we are okay. clang-tidy did miss a few `= delete`s, though; I'll push an update to this branch.

**Comment by drwells** [comment]
Automatically rewriting all the comments will take a bit of work, but I think I know how to script it.

**Comment by drwells** [comment]
Yes. Lets get merge so that we can get on with the SAMRAI 3 migration. I'll open a separate issue for rewording the documentation. I will get on that in a day or two when I need something less exciting to do :)

**Pull request merged**
