### PR TITLE
start removing templates on NDIM

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format (i.e., `make indent`) run? For more information see
      `scripts/formatting/README.md`.
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
So before we do something like this I think we need to agree on the workflow we're going to use for upgrading to SAMRAI 4 - via the email, I think both Amneet and I would prefer that these kinds of upgrades are reproducible via script. Can you put the commands you used in a script instead of committing things here?

**Comment by boyceg** [comment]
> So before we do something like this I think we need to agree on the workflow we're going to use for upgrading to SAMRAI 4 - via the email, I think both Amneet and I would prefer that these kinds of upgrades are reproducible via script. Can you put the commands you used in a script instead of committing things here?

Yes, this is all being done using a simple script (currently named `modernize.sh`).

**Comment by drwells** [comment]
GitHub's UI is really struggling with a patch this large. Could you put that script in a separate commit?

**Comment by boyceg** [comment]
I am almost done purging `NDIM` --- I'll make a separate branch with just the script and interface header once it is done.

**Comment by boyceg** [comment]
@drwells see #1730 for just the basic scripts and headers.

**Pull request closed without merging**
