### PR TITLE
AminKolah/merge-surface-jumps

### PR DESCRIPTION
**Pull request by AminKolah**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
@AminKolah, can you confirm that this branch give the same results as in the paper? If so, I can try to rework history tonight.

**Comment by boyceg** [comment]
Actually, this PR does not seem to have any of the new jump condition computations (e.g. for the viscous stress). What is the intent for this branch; is it supposed to include all IIM stuff?

**Comment by AminKolah** [comment]
@boyceg there was a merge conflict that I just fixed...Is history still problematic?

**Comment by boyceg** [comment]
Are you trying to split into smaller commits? This is not the full IIM implementation, is it?

**Comment by AminKolah** [comment]
I believe it is, what is missing exactly?

**Comment by AminKolah** [comment]
Also this is working for ex5 of IBFE giving the right CD/CL using the traction. I can test it with a few RBD tests too.

**Comment by boyceg** [comment]
> I believe it is, what is missing exactly?

Hmmm, GitHub was not showing me all of the changes in `IBFESurfaceMethod.cpp`, but now it is.

Are you tinkering with this? Can we "freeze" it for a few days so I can try to break it up into smaller chunks?

**Comment by AminKolah** [comment]
> > I believe it is, what is missing exactly?
> 
> Hmmm, GitHub was not showing me all of the changes in `IBFESurfaceMethod.cpp`, but now it is.
> 
> Are you tinkering with this? Can we "freeze" it for a few days so I can try to break it up into smaller chunks?

No, this is exactly the same version we were looking at a month ago. I rebased with `master` to incorporate new changes but then I noticed `IBFESurfaceMethod.cpp` wasn't properly update after merge conflict. So I made another push to fix it. The history still seems kinda messed up I guess after the rebase....Sure I won't touch it

**Comment by boyceg** [comment]
Let's close this in favor of #932 and friends.

**Pull request closed without merging**
