### PR TITLE
Output strain rate

### PR DESCRIPTION
**Pull request by abarret**
Added functionality to compute the cell-centered strain rate from a side-centered vector field, i.e. E = 0.5*(grad(u) + grad(u)^T).

Also adds the option to output the fluid strain rate to viz files, defaults to false.

### CODE REVIEW

**Comment by deleeke** [comment]
retest this please
(I think there may have been a problem with config.cache on this last opt build)

**Comment by boyceg** [comment]
In the function calls, should strain --> strain_rate?

**Comment by abarret** [comment]
That's probably a good idea. Should I also change all variables to strain_rate?

**Comment by boyceg** [comment]
I just did it. I will merge once Jenkins reports back clean builds.

**Pull request merged**
