### PR TITLE
update algorithm to order perimeter nodes for the meter meshes

### PR DESCRIPTION
**Pull request by boyceg**
Similar to #1508 but with what I think is a simpler algorithm.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
Could we pull out the problematic node set to validate this outside of the heart model?

**Comment by boyceg** [comment]
> Could we pull out the problematic node set to validate this outside of the heart model?

A reasonable test would be one in which the node set does not contain all of the perimeter nodes --- that was the case that we needed to handle in the heart model.

**Comment by boyceg** [comment]
It looks like my algorithm does not give the same orientation as @cpuelz's. Presumably it has to do with the way that the second node is chosen.

**Review by cpuelz — APPROVED** [review]

**Comment by cpuelz** [comment]
> > Could we pull out the problematic node set to validate this outside of the heart model?
> 
> A reasonable test would be one in which the node set does not contain all of the perimeter nodes --- that was the case that we needed to handle in the heart model.

we could do that... we just need to get the elements as well?

**Comment by cpuelz** [comment]
> It looks like my algorithm does not give the same orientation as @cpuelz's. Presumably it has to do with the way that the second node is chosen.

yeah, I am sure that's what happened... not an issue.

**Comment by boyceg** [comment]
@drwells @cpuelz I have updated the tests ... let's see what the CI says.

**Comment by boyceg** [comment]
Supersedes #1508.

**Comment by drwells** [comment]
Can you rebase?

**Comment by boyceg** [comment]
Done.

**Comment by boyceg** [comment]
I think this is ready to merge once the CI is happy.

**Comment by boyceg** [comment]
@drwells: all tests are passing now; shall we merge?

**Comment by boyceg** [comment]
Oh I guess there is no test.

**Comment by drwells** [comment]
I wrote a quick test on my own by adding
```cpp
        const bool skip_some_nodes = input_db->getBoolWithDefault("skip_some_nodes", false);
        if (skip_some_nodes)
        {
            for (auto node_it = mesh.nodes_begin(); node_it != end_node_it; ++node_it)
            {
                Node& node = **node_it;
                // outline the bottom face with id 10 but skip some nodes
                if (node(2) == 0.0 && (node(0) == 0.0 || node(0) == 1.0 || node(1) == 0.0 || node(1) == 1.0))
                    if (node(0) != 0.0 && node(0) != 1.0)
                        boundary_info.add_node(&node, 10);

                // outline the top face with id 100: also skip some nodes
                if (node(2) == 1.0 && (node(0) == 0.0 || node(0) == 1.0 || node(1) == 0.0 || node(1) == 1.0))
                    if (node(1) != 0.0 && node(1) != 1.0)
                    boundary_info.add_node(&node, 100);
            }
        }
        else
        {
            for (auto node_it = mesh.nodes_begin(); node_it != end_node_it; ++node_it)
            {
                Node& node = **node_it;
                // outline the bottom face with id 10
                if (node(2) == 0.0 && (node(0) == 0.0 || node(0) == 1.0 || node(1) == 0.0 || node(1) == 1.0))
                    boundary_info.add_node(&node, 10);

                // outline the top face with id 100
                if (node(2) == 1.0 && (node(0) == 0.0 || node(0) == 1.0 || node(1) == 0.0 || node(1) == 1.0))
                    boundary_info.add_node(&node, 100);
            }
        }
```
This crashes on master - I'm checking a few more things to see why before I check if it works with this patch.

**Comment by boyceg** [comment]
It should crash on master I think. 😁

**Comment by drwells** [comment]
it does!

**Review by drwells — APPROVED** [review]
This change looks good and my test code passes with it - I'll add the test in a followup PR.

**Pull request merged**
