### PR TITLE
Source copyright

### PR DESCRIPTION
**Pull request by drwells**
First half of #604: I'll put up a followup PR later that implements the same fix for automake etc. files.

### CODE REVIEW

**Comment by boyceg** [comment]
Is there a script to do this stuff? I would like to use it to update copyright in the pending NWT branch.

**Comment by drwells** [comment]
I wrote a python script for it but it currently isn't smart enough to not try and 'fix' files whose copyright statement has already been updated. I'll post a fixed version here in a bit.

**Comment by drwells** [comment]
Try this for source and header files:
```python
#!/usr/bin/env python2

import os
import subprocess

def main():
    top_directories = ["./ibtk/include", "./ibtk/src", "./ibtk/examples",
                       "./src", "./include", "./examples", "./tests"]
    files = list()
    for top_directory in top_directories:
        for root, _, file_names in os.walk(top_directory):
            for file_name in file_names:
                if file_name.endswith('.h') or file_name.endswith('.cpp'):
                    files.append(root + os.sep + file_name)

    for file_name in files:
        contents = list()
        found_end_of_copyright = False
        file_already_updated = False
        with open(file_name, 'r') as file_handle:
            for line in file_handle.readlines():
                if found_end_of_copyright:
                    contents.append(line)
                else:
                    if "SUCH DAMAGE." in line:
                        found_end_of_copyright = True
                    elif "by the IBAMR developers" in line:
                        file_already_updated = True
                        break

        if not file_already_updated:
            # output is 2019\n2018\n etc.
            years = subprocess.check_output(
                ["git", "log", "--format=format:%cd", "--date=format:%Y",
                file_name])
            # TODO: this string handling is probably not compatible with python3
            copyright_start = str(years[-4:])
            copyright_end = str(years[:4])

            message = \
"""// ---------------------------------------------------------------------
//
// Copyright (c) {} - {} by the IBAMR developers
// All rights reserved.
//
// This file is part of IBAMR.
//
// IBAMR is free software and is distributed under the 3-clause BSD
// license. The full text of the license can be found in the file
// COPYRIGHT at the top level directory of IBAMR.
//
// ---------------------------------------------------------------------
""".format(copyright_start, copyright_end)

            # some files don't have a copyright statement at all, so dump everything
            # into their contents
            if not found_end_of_copyright:
                with open(file_name, 'r') as file_handle:
                    for line in file_handle.readlines():
                        contents.append(line)

            if contents[0] != "\n":
                contents = ["\n"] + contents

            with open(file_name, 'w') as file_handle:
                file_handle.write(message)

                for line in contents:
                    file_handle.write(line)

if __name__ == '__main__':
    main()
```

**Comment by drwells** [comment]
Lets hold off on merging this until #744 is done: we don't need multiple commits for updating copyrights.

**Comment by drwells** [comment]
#744 is in so lets merge this now.

There will always be a few files which are out of sync (at least until we get all active branches merged) so I also added 'rerun the copyright script' to the release tasks document.

**Pull request merged**
