### PR TITLE
Add a template for pull requests.

### LINKED ISSUE #900: Add PR checklist
We should put together a little checklist for PRs of common mistakes, e.g., forgetting to make things work with restart.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #900. After this is merged the following text should appear, by default, in every new PR:

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

Are we all okay with this list?

### CODE REVIEW

**Comment by boyceg** [comment]
Looks good to me.

**Comment by drwells** [comment]
@abarret @amneetb are you two happy with this list? Before we agree on it I would like to get all the administrators' feedback/approval.

**Comment by abarret** [comment]
Do we want to include reminders about setting labels or reviewers?

**Comment by drwells** [comment]
We should include labels. We usually don't set reviewers, though - what should we change about the current process where whoever has time does the review?

**Comment by abarret** [comment]
I've never been sure about when to review PRs. I tend to only review when asked or if the PR is relevant to the portion of the code I work on.

I'm fine with the status quo. I'm just not entirely sure what it is :)

**Comment by drwells** [comment]
I try to review any open PR that I understand if I can find some time in which I can do it. I usually review IBFE PRs since I know that area quite well.

**Comment by drwells** [comment]
Everyone seems okay with the first iteration of this little checklist so lets merge. We'll see if I set things up correctly so that the default text pops up :)

**Pull request merged**
