### PR TITLE
Fixed a bug in numerical wave tank test

### PR DESCRIPTION
**Pull request by Raamkrishnan**
Hi @drwells,

I fixed the bug. Could you please rerun the test with this updated code?

### CODE REVIEW

**Comment by drwells** [comment]
Do we need to make the same change in the examples? It looks like this class only now works if we make one more function call.

**Comment by Raamkrishnan** [comment]
In examples, only IBLevelSet/ex0 uses FESurfaceDistanceEvaluator class. I already included this function call and checked it. However, I forgot to include in tests/wave_tank.

**Comment by drwells** [comment]
I'd like @amneetb to take a look since this means we have to call the class in a different way now.

**Comment by drwells** [comment]
Fixes #850.

**Comment by amneetb** [comment]
Looks good. The routine is broken for efficiency reasons. (For pure translation, surface normals would remain the same, so no need to recompute them)

**Comment by drwells** [comment]
@amneetb is happy so lets merge!

**Pull request merged**
