### PR TITLE
ensure that regridHierarchyConfiguration is called when expected

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by boyceg** [comment]
Note that this drops some commits from #1555 to restore the original behavior of `AdvDiffHierarchyIntegrator` / `AdvDiffSemiImplicitHierarchyIntegrator` --- and so the history is screwy.

**Comment by boyceg** [comment]
Implementations of `HierarchyIntegrator::resetHierarchyConfiguration` often assume that function is called any time there is a change to the patch hierarchy, but SAMRAI appears not call that function if the only change to the hierarchy is that the finest level was dropped. In this PR, there is extra logic to see if the number of levels changed but `HierarchyIntegrator::resetHierarchyConfiguration` was not called.

@amneetb, I think this is a simpler fix than what is in #1555 and #1567.

The other issue is that many of the solver objects' deallocation routines break if the number of levels changes. I think that the right fix is to make sure that the deallocation routines work if the number of levels changes. This mostly entails extra calls to `SAMRAIVectorReal::resetLevels`. I started doing that here.

**Comment by boyceg** [comment]
The relevant changes (so far) are:
* https://github.com/IBAMR/IBAMR/pull/1585/commits/73c2247b0d044db3cb37e90c7bcb8a6eb0465e93
* https://github.com/IBAMR/IBAMR/pull/1585/commits/daf1b390cf056862b31fe7b78be77ef06e593015

**Comment by drwells** [comment]
Can you explicitly use `git revert` so that the history is cleaner? That would help me understand where the new stuff is.

**Pull request closed without merging**
