### PR TITLE
eliminating some calls to NumericVector<T>::close()

### PR DESCRIPTION
**Pull request by boyceg**

### CODE REVIEW

**Comment by drwells** [comment]
Excellent. I'll take a look :)

**Comment by boyceg** [comment]
I think that I really am done with this now.

**Comment by boyceg** [comment]
(I have to admit that I am not crazy about the way I have set up the new helper functions that take in `vector<vector<vec*>>`.)

**Comment by boyceg** [comment]
Just a heads up --- it looks like this does affect the answer generated in ex0 slightly. 👎

**Comment by drwells** [comment]
This is another reason why we need parallel tests. I will eek out a few more hours to work on that this week.

**Comment by boyceg** [comment]
This PR is superseded by #433, which fixes the bugs that worked their way into this PR.

**Pull request closed without merging**
