### PR TITLE
Fix child integrator test that fails in debug mode.

### PR DESCRIPTION
**Pull request by abarret**
Fixes a failing test pointed out in #1307. First, `d_current_cycle_num` was not being incremented correctly by the dummy integrator. This causes it to fail when `NDEBUG` is not defined. Second, the input and output files were not named correctly, so the test never ran in `attest`.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Review by boyceg — APPROVED** [review]

**Comment by kwryankrattiger** [comment]
I am seeing difference in the output for this case after a rebase. Can you confirm?

[LastTest.log](https://github.com/IBAMR/IBAMR/files/6902972/LastTest.log)

**Comment by abarret** [comment]
> I am seeing difference in the output for this case after a rebase. Can you confirm?
> 
> [LastTest.log](https://github.com/IBAMR/IBAMR/files/6902972/LastTest.log)

It appears that the tester has been built without support for Silo, is that correct? I'm seeing warnings about not having Silo available.

**Comment by drwells** [comment]
@abarret could you apply the fix from #1283 also here?

**Comment by drwells** [comment]
or just disable plotting output completely - both work.

**Comment by kwryankrattiger** [comment]
SILO should be enabled for this build, everything should be turned on AFIAK. It is strange that it is printing an error for this case but none of the other tests that use SILO.

**Pull request merged**
