### PR TITLE
Remove bug related to homogeneous boundary conditions and Add AMR to examples/adv_diff_ex8

### PR DESCRIPTION
**Pull request by Raamkrishnan**
…_diff/ex8

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

I removed a bug related to homogeneous boundary conditions in ```BrinkmanAdvDiffBcHelper``` class and also made changes related to AMR in the examples/adv_diff/ex8. Please take a look and let me know your suggestions.

### CODE REVIEW

**Review by amneetb — APPROVED** [review]

**Comment by amneetb** [comment]
@Raamkrishnan: Looks good. Once @drwells approves it you can merge this with master.

**Review by drwells — CHANGES_REQUESTED** [review]
Can you add the items on the PR checklist?

**Comment by Raamkrishnan** [comment]
@drwells @amneetb I have added a new test to solve the Poisson problem with the homogeneous Neumann boundary condition. I have also added a change log. Please take a look.

**Review by drwells — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
