### PR TITLE
Fixing CIB and its examples

### PR DESCRIPTION
**Pull request by amneetb**

### CODE REVIEW

**Comment by boyceg** [comment]
I got rid of those calls to `std::make_pair` --- looks cleaner to me, but YMMV.

**Comment by amneetb** [comment]
I have learnt all my internet acronyms from you ;-) . 

Looks like C++ is becoming more like MATLAB, cryptic yet sleek. Will follow this initialization style moving forward. There should be some doc page on ibamr.github.io on new C++ style to ensure uniformity among all developers.

**Comment by boyceg** [comment]
Could you give that a whirl?

**Comment by amneetb** [comment]
OK, this made it work. As you pointed out earlier, it is imperative to scrutinize #380 under a microscope.

**Pull request merged**
