### PR TITLE
Revert "Use FEValues in FEDataInterpolation."

### PR DESCRIPTION
**Pull request by drwells**
This reverts commit 5dba10c26cfe55027d47cbebee88d63d5d0ff0f1.

This feature passes the test suite but causes problems in user codes
that we don't currently have time to address.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
@jabrown893 @marshallrdavey could you take a quick look, before we merge, and make sure that this fixes your problems?

Also, @jabrown893: I still want to meet to try and fix the bug that occurred with this patch so that I at least know what went wrong.

**Comment by jabrown893** [comment]
Which bug is this supposed to fix? The issues with using nodal quadrature or the random seg faults?

**Comment by drwells** [comment]
The issue with nodal interpolation (where things fail in a weird way inside FEDataInterpolation).

**Comment by drwells** [comment]
This fix fixes @jabrown893's case with nodal quadrature, so lets merge.

**Comment by drwells** [comment]
We need to double-check that previous statement - hold on.

**Comment by jabrown893** [comment]
Yes, this does fix one of the errors I was experiencing with nodal quadrature (the boost error)

**Comment by drwells** [comment]
@marshallrdavey that should fix the problem you reported - let me know if it does not.

**Pull request merged**
