### PR TITLE
NWT: multiphase_flow examples 7, 8, and 9

### PR DESCRIPTION
**Pull request by drwells**
Part of #546. As mentioned in #546 we cannot merge this until `ConstraintIBMethod::getFullLagrangeMultiplierForce` and `ConstraintIBMethod::getInterpolatedLagrangianDensity` are in the library: hence this is `do not merge` until we get that done.

### CODE REVIEW

**Comment by drwells** [comment]
As @amneetb mentioned: removing the postprocessing calls fixes the compilation issue, so this is OK to review now.

**Comment by drwells** [comment]
I force pushed a change to the commit in this PR that includes all other changes made to these examples.

**Comment by boyceg** [comment]
> Looks like some of the source code files could use a run through `clang-format`. (There is some very minor formatting stuff in the comments, maybe a few other things.) Otherwise looks fine.

One other minor thing --- looks like these examples are using raw pointers in places where we probably could be using something like `std::unique_ptr` instead. There are probably existing examples that do this as well.

**Comment by boyceg** [comment]
> > Looks like some of the source code files could use a run through `clang-format`. (There is some very minor formatting stuff in the comments, maybe a few other things.) Otherwise looks fine.
> 
> One other minor thing --- looks like these examples are using raw pointers in places where we probably could be using something like `std::unique_ptr` instead. There are probably existing examples that do this as well.

Finally, another minor thing --- for static functions that are not associated with a class, I think that we try to use lowercase + underscores instead of camel case, although I do not think that we are 100% consistent on this.

**Comment by drwells** [comment]
I must admit I didn't read the source code. I'll take a look (and run clang-format).

**Comment by boyceg** [comment]
I don't think we necessarily need to address all of this in the source before merging. We have not run modernize on the examples yet, and at some point we need to do something to cut down on the boilerplate code that shows up in all of them.

**Comment by drwells** [comment]
I just rebased this on top of master to get the `ln` fix in #551.

**Comment by drwells** [comment]
Per our conversations elsewhere: the examples in #418 are okay as-is. I will run clang-format and spot check this and merge it later today unless there are new objections.

**Comment by drwells** [comment]
example 8 is missing `sphere3d.vertex`. @amneetb do you remember which input file we should use here? The other two copies of this file `ConstraintIB/falling_sphere/sphere3d.vertex` and `IB/explicit/ex1/sphere3d.vertex` are not equal.

Otherwise this is ready to go.

**Comment by amneetb** [comment]
Looks like @nishantnangia forgot to add this here. If you type `make examples` in this directory it will generate a binary for generating sphere3d.vertex (simply executing the binary will generate the vertex file). I can do that and send it to you over the email. There are two branches multiphase-examples. Which one should I use?

**Comment by drwells** [comment]
I don't see this executable. The branch is `multiphase-examples` (i.e., the first one).

**Comment by amneetb** [comment]
I just emailed you the vertex file for this example. He forgot (or perhaps did not intend to) to create a separate executable for generating vertex file, which is also fine. Just doing `g++ sphereGen.cpp -o ./exe` creates the executable. No need to to have a target in the Makefile.am for this simple code.

**Comment by boyceg** [comment]
Might as well have the make target, but no need to build it unless requested.

**Comment by drwells** [comment]
These vertex files are huge: the 3D file is 9 MB (for comparison: `./src` is 5MB).

Does anyone object to simply generating the vertex files as part of the build process? This would make the PR a lot smaller.

**Comment by boyceg** [comment]
> Does anyone object to simply generating the vertex files as part of the build process? This would make the PR a lot smaller.

This sounds like a good idea to me.

In fact, I was just thinking about whether we should aim to do this for all of the tests. It probably would not be too hard to convert the existing MATLAB scripts that build these meshes into Python scripts. It seems crazy to carry around these gigantic text files full of mesh coordinates.

**Comment by drwells** [comment]
Done.

I checked that all the examples run so this is now good to go.

**Comment by boyceg** [comment]
Feel free to merge once Jenkins gives the 👍.

**Comment by drwells** [comment]
I also added a changelog so that @nishantnangia gets credit!

**Comment by boyceg** [comment]
I created an issue (#560) on getting rid of the mesh data files.

**Comment by amneetb** [comment]
> These vertex files are huge: the 3D file is 9 MB (for comparison: `./src` is 5MB).
> 
> Does anyone object to simply generating the vertex files as part of the build process? This would make the PR a lot smaller.

For this particular example, we can generate the vertex file as a part of `make examples` process, i.e, build and run the executable for generating vertex file during `make examples`.

**Comment by amneetb** [comment]
> I also added a changelog so that @nishantnangia gets credit!

Thanks to both @drwells and @nishantnangia!

**Comment by drwells** [comment]
of course :)

**Pull request merged**
