### PR TITLE
PCFIELDSPLIT smoother via PETSc option files

### PR DESCRIPTION
**Pull request by amneetb**
-- PCFIELDSPLIT smoother for Stokes-IB.
-- PETSc command lines via option file for tests/Stokes-IB.

### CODE REVIEW

**Comment by amneetb** [comment]
@boyceg : Could you try Stokes-IB/test1?

**Comment by amneetb** [comment]
@boyceg: Check the PETSc command line for level solvers.

**Comment by boyceg** [comment]
Works for me.

**Comment by boyceg** [comment]
Please don't merge master into a PR before merging the PR into master unless you really have to to get a clean merge of the PR to master. It muddies up the history with commit messages like:

Merge branch 'master' into amneetb/add-petsc-options-file <https://github.com/IBAMR/IBAMR/commit/e37f596bb20358250686a08fa3dc4e083c8b3b1a>

**Pull request merged**
