### PR TITLE
support for "augmented" linear solves

### PR DESCRIPTION
**Pull request by boyceg**
We need support for solving systems of equations that involve "extra" variables (in addition to Cartesian grid data).

### CODE REVIEW

**Comment by boyceg** [comment]
@amneetb This is my stab at an augmented solver. Note that the solver is set up to make it easy to continue to use standard Cartesian grid solvers. There is are extra MatVecMult and PCApply functions to be defined in subclasses to control how the extra variables are coupled to the rest of the system.

**Comment by boyceg** [comment]
Although now that I have created the PR, it occurs to me that it might be better to request users to supply the "coupling" operators directly (e.g. as Mat and PC objects).

**Comment by amneetb** [comment]
Looks good. I think for initializing extra_vec's one will need to pass in Vecs of these kinds.

**Comment by boyceg** [comment]
The intent is that users set these when using the subclass before calling solve. It is clunky.

**Comment by boyceg** [comment]
@amneetb Revised this using MatNest. Still missing support for custom preconditioning, but I think this is less clunky than the previous design.

**Pull request merged**
