### PR TITLE
Consistently check ifstream states.

### LINKED ISSUE #413: IBStandardInitializer should fail when file exists but not readable
`IBStandardInitializer` quietly ignores files that can't be opened. It should either quit or at least emit a helpful warning message.

C++ seems to be ill equipped to deal with this. As @drwells pointed out, we can either use C++17's file system library (which requires C++17), boost's version of the file system library (which requires a compiled boost build), or stat (which is non-standard). None of these options are ideal, but stat seems to be the least intrusive option. We could also just leave this as a "feature" of IBAMR. @boyceg, do you have any opinions?

### PR DESCRIPTION
**Pull request by drwells**
Ensure that we actually opened the file in all cases.

Fixes #413 and #643.

### CODE REVIEW

**Comment by drwells** [comment]
I think the CI infrastructure is down: I get 404s when I click on the `Details` link.

**Comment by drwells** [comment]
This approach won't work: `IBStandardInitializer` loads files based on whether or not they exist. This patch causes the multiphase tests to fail since they only load vertex files and ignore the rest.

We can resolve this by consistently checking that the file stream was opened successfully, but any other checks will break peoples codes.

**Comment by boyceg** [comment]
> This approach won't work: `IBStandardInitializer` loads files based on whether or not they exist. This patch causes the multiphase tests to fail since they only load vertex files and ignore the rest.

Yes, that is right --- there is one required file and several optional files that are used by `IBStandardInitializer`. If the optional files are not present, then they are skipped (with a log message).

**Comment by drwells** [comment]
I don't think we consistently log that files are skipped. Should we?

**Comment by boyceg** [comment]
I think that we log that certain things are "skipped". Maybe we don't?

**Comment by drwells** [comment]
We do not: e.g., if the spring files do not exist we silently continue. Lets add it.

**Comment by drwells** [comment]
I fixed the merge conflict.

**Comment by drwells** [comment]
Thats a tricky question to answer. I think that users are more likely to look at the logfile than the slurm output so I think the current option (plog) is the right one.

**Comment by drwells** [comment]
@boyceg are you okay with not making further changes? If so lets merge.

**Comment by drwells** [comment]
@boyceg can we merge?

**Comment by boyceg** [comment]
Oh, sorry, I thought I already approved.

**Comment by drwells** [comment]
You did but I wanted to be sure you were OK with the bit on plog vs pout.

**Pull request merged**
