### PR TITLE
lazy initialize IB ghosted DOF indexing

### LINKED ISSUE #947: Call FEDataManager::reinitElementMappings() by request for each system
I ran callgrind on TAVR again over the weekend and took a look at the results. I don't have time to work on this now but I figured we should summarize the problem so that we don't forget about it.

Some applications add a lot of their own libMesh systems to the EquationSystems object managed by FEDataManager - most of these never need to access the IB-ghosted partitioning, but we still unconditionally compute this partitioning for them in `reinitElementMappings()`. This problem is made worse by use of the scratch hierarchy where we do everything for both the primary and scratch partitioning. Since the TAVR code regrids a lot this ends up occupying 15% of our total run time.

We should modify the logic to only compute `d_active_patch_ghost_dofs` and `d_system_ib_ghost_vec` on demand instead - this should largely resolve the problem since we rarely access this information for more than two systems (instead of assembling it, for the TAVR case, for about 10 systems).

### PR DESCRIPTION
**Pull request by boyceg**
Fixes #947.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
> 198/314 (63.06%) tests passed

At a glance the implementation looks fine but it doesn't work. Can you try running some IBFE examples locally to figure this out?

**Comment by boyceg** [comment]
fixing now

**Comment by boyceg** [comment]
I forgot to initialize the data structures in `buildIBGhostedVector`.

**Comment by boyceg** [comment]
I had to remove the `const` qualifier from `buildIBGhostedVector`. I'm running the test suite now on my Mac.

**Comment by boyceg** [comment]
BTW, the testsuite takes forever to run on my Mac. Any tricks for making it run faster? :-)

**Comment by drwells** [comment]
For something like this I recommend only running IBFE tests: try `./attest -j -R IBFE` (here `IBFE` is a regular expression).

How slow is slow? I can complete `./attest -j6` on my desktop (which has four physical processors and circa 2013 hardware) in about ten minutes.

**Comment by boyceg** [comment]
Debug or opt mode? Much slower for me...

**Comment by drwells** [comment]
optimized mode.

**Comment by boyceg** [comment]
Ah, I see -- I've been running a debugging build.

**Comment by drwells** [comment]
I'm not exactly sure what is going on but libMesh does a ton of extra checking in debug mode for parallel computations that slows it down by more than an order of magnitude. I almost always run the test suite in optimized mode to avoid this problem.

**Comment by jabrown893** [comment]
Would it be helpful for me to test this on some TAVR code, or is there anything else I can ran to help test?

**Comment by drwells** [comment]
This looks reasonable and passes the test suite so lets merge.

@jabrown893 if you already have some timing data for the TAVR code it would be useful to compare these changes against that. I'm also going to rerun things in callgrind to get some more precise readings.

**Pull request merged**
