### PR TITLE
CMake: Add install target for examples

### PR DESCRIPTION
**Pull request by kwryankrattiger**
### IBAMR Pull Request Checklist
- [ ] Does the test suite pass?
- [ ] Was clang-format run?
- [ ] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [ ] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Review by drwells — CHANGES_REQUESTED** [review]
We cannot use cmake_path since it was added in CMake 3.20. In particular, Ubuntu 20.04 ships CMake 3.16 - we really cannot use a newer version than that, and I would prefer to stick to 3.15.

**Comment by boyceg** [comment]
I'm not sure that I follow what is going on here. Does this mean that you have to decide whether or not to build examples at configure time?

**Comment by drwells** [comment]
That is part of the change in this PR, though its not in the CMake build system right now. Presently examples are always set up (i.e., we unconditionally generate Makefiles for them) but you have to type `make examples` to compile them: they aren't part of the `all` target (what gets compiled when you just type `make`).

Our colleagues at kitware pointed out here and in other patches that I set things up in a more autotools-like way rather than idomatic CMake: with autotools we still write makefiles and defining separate `make tests` and `make examples` targets makes sense. With CMake, though, it is more common to do `cmake -DBUILD_EXAMPLES=ON` or `cmake -DBUILD_EXAMPLES=OFF` and then `make` will compile or not compile examples (i.e., no separate `make examples`). I like excluding these from `all` but there are good reasons to do it this way.

**Comment by boyceg** [comment]
I think I would prefer to keep separate make targets for examples and tests by default, but possibly allow users to include flags at configure time to "add" examples or tests to `make all` if they want.

**Comment by boyceg** [comment]
@drwells should we finish this one too?

**Comment by boyceg** [comment]
@drwells: you are the CMake boss, so it is really up to you.

**Comment by drwells** [comment]
In that case I will close for now, at least until we get a compelling use-case.

**Pull request closed without merging**
