### PR TITLE
HierarchyIntegrator now always regrids before the first time step

### PR DESCRIPTION
**Pull request by drwells**
Another independent commit from #744. Once we merge this we can just delete the commit there.

### CODE REVIEW

**Comment by drwells** [comment]
Hm - not all tests pass this way, even though they passed with the other branch. There must be another change lurking around.

**Comment by boyceg** [comment]
There are some changes in the INS integrators related to where regrid projections are implemented, although nothing that I would expect to change output -- I think the operations should be the same as before.

**Comment by drwells** [comment]
It changes the output in a very minor way - we print an additional logging message stating where (i.e., in which function) we regrid. None of the computed output actually changes.

I merged the two commits together so that we don't have a commit in our history where half the tests no longer pass.

**Comment by boyceg** [comment]
@drwells can we merge?

**Comment by drwells** [comment]
Yup. I will rebase #744 afterwards.

**Pull request merged**
