### PR TITLE
Fe values codim

### PR DESCRIPTION
**Pull request by drwells**
This PR actually uses the new `FEValues` class - it should make IBFE programs run about 5-10% faster (based on how large their structures are).

I also added a horrible test based on a klein bottle to really check that we get the same values as libMesh. Here's the mesh:

klein

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by drwells** [comment]
Part of #482.

**Comment by boyceg** [comment]
There are a number of places where we still us `FEBase` directly --- are any of those candidate for replacement by `FEValues`?

**Comment by drwells** [comment]
Yes, but this replacement class is still not full-featured (e.g., we do not yet know how to compute normal vectors).

I started here since `FEDataInterpolation` takes up a huge amount of our total runtime.

**Comment by drwells** [comment]
Part of why I went to all this effort to add a tricky test was to make it easier in the future to implement normal vectors and be able to show that we get the same thing as libMesh.

**Pull request merged**
