### PR TITLE
Fix compilation with clang

### PR DESCRIPTION
**Pull request by drwells**
It looks new versions of clang are more pedantic than my installation of GCC - the functor objects provided for sorting inside `std::set` and `std::map` must have a const calling operator, i.e., `operator()(const T&a, const T&b) const`.

I meant to delete some logging statements in this code before merging #832; I put those changes in this PR too.

### CODE REVIEW

**Comment by drwells** [comment]
@jabrown893 Would you please check that this patch fixes things for you?

**Comment by jabrown893** [comment]
@drwells Seems to fix things!

**Comment by drwells** [comment]
uh oh - the CI failed with `no space left on device`.

**Comment by drwells** [comment]
Lets try the easy thing first:

Jenkins retest this please

**Pull request merged**
