### PR TITLE
Rearrange load balancer

### PR DESCRIPTION
**Pull request by drwells**
I spent a large part of today reviewing how we (and SAMRAI) do load balancing. This little PR is the first step in utilizing SAMRAI's very nice infrastructure for doing nonuniform load balancing: it just moves some code around so that we can get a load balancer in INSHierarchyIntegrator.

### CODE REVIEW

**Comment by boyceg** [comment]
What is the benefit of each of these classes having a `worload_var` and `workload_idx`? (I ask this question fully realizing that I am the one that started this particular practice.) I wonder if this should just be owned by the parent `HierarchyIntegrator` and then passed around as needed to fill in the workload estimates.

**Comment by drwells** [comment]
By these classes, do you mean the Hierarchy classes, or things like FEDataManager?

**Comment by drwells** [comment]
Hm. The only things we do with the load balancer are to call `load_balancer->setWorkloadPatchDataIndex` and `load_balancer->setUniformWorkload`. Neither of those are really the concern of the HierarchyIntegrator but it means we will have to set it up somewhere else.

**Comment by boyceg** [comment]
Yeah, one of these classes needs to manage allocation for the workload index data. I usually put that into the integrator, but agree that there is probably a better place.

We probably do not need to handle non uniform load balancing except for applications using IB, so it could possibly just go into IBStrategy, and no where else.

**Comment by boyceg** [comment]
This is fine for now; I will go ahead and merge.

**Comment by drwells** [comment]
I'm still thinking about how to do this: i.e., `FEDataManager` only needs the workload index.

**Comment by boyceg** [comment]
> I'm still thinking about how to do this: i.e., FEDataManager only needs the workload index.
> 
LDataManager could use it too in an IBMethod-based simulation.

**Pull request merged**
