### PR TITLE
fix contrib dir path in ibtk

### PR DESCRIPTION
**Pull request by boyceg**

### CODE REVIEW

**Comment by boyceg** [comment]
I am surprised that "bundled" versions of Boost, Eigen, and muParser worked when compiling the IBTK library.

**Comment by drwells** [comment]
I have definitely used these. How bizarre!

**Comment by drwells** [comment]
There is an easy explanation for boost and eigen: the second argument refers to the build directory. Since there is nothing to build, the second argument is never used.

For muParser: this is a link to the directory in which we build it: in principle we could set this value to something completely arbitrary since `configure` will correctly set up the path to the library based on the supplied value.

**Comment by boyceg** [comment]
Without this change, IBTK builds fine, but IBTK examples do not.

(Because of reasons, running `make examples` in the IBAMR build directory only compiles the IBAMR examples and not the IBTK examples.)

**Comment by drwells** [comment]
Hm, I must have misunderstood the IBTK configuration script.

**Comment by drwells** [comment]
I don't fully understand how the paths work but I can verify that the problem exists on master and this branch fixes it.

**Comment by boyceg** [comment]
> I don't fully understand how the paths work but I can verify that the problem exists on master and this branch fixes it.

Because IBTK is a full-fledged Automake package, its top-level build directory is `/path/to/ibamr-build-dir/ibtk`.

**Pull request merged**
