### PR TITLE
Include a python script Aaron wrote.

### PR DESCRIPTION
**Pull request by drwells**
This should also now work with python 3.

@jabrown893 Two things:
1. Would you please try out this version of the script with both python 2 and python 3 to make sure it works with both?
2. I didn't read the script very carefully. Is the summary of it in the changelog entry correct?

### CODE REVIEW

**Comment by jabrown893** [comment]
@drwells 
1. It appears to work with both python 2 & python 3.

**Comment by jabrown893** [comment]
@drwells 
2. I think the description is pretty much right. Maybe add that it lists all the data files inside the files named dumps.visit and lag_data.visit.

**Comment by drwells** [comment]
Thanks. I also added a documentation string to the script to record how it works.

**Comment by drwells** [comment]
Since this PR only adds a script that is never executed by travis I will merge as-is without waiting on the CI build.

**Pull request merged**
