### PR TITLE
Add a new class FEPatchData.

### PR DESCRIPTION
**Pull request by drwells**
This class supersedes the current `SystemDofMapCache` system: it stores all FE indices on patches, as well as localized indices for direct access to ghosted vectors in contiguous buffers (instead of `std::map<int, std::vector<std::vector<int>>>`). I use the very nice `boost::const_multi_array_ref` to return multidimensional views into aforementioned buffers that interoperate well with other functions in IBTK.

This is part of the fix to 'how do we assemble efficiently when we have a lot of nonlocal data' from #492: in particular, this implements indices for directly accessing ghosted vectors via standard pointer arithmetic.

This is definitely a work in progress: the implementation is mostly done but we don't actually use it anywhere yet. We have a bunch of stuff to do along the way:
- [ ] Consider deprecating `SystemDofMapCache` unless it is sufficiently convenient to keep around
- [ ] Add a `std::vector<FEPatchData>` member to `FEDataManager` and update it after regridding. Also add some warnings to that class that inform users that `FEDataManager` caches a lot of data and said caches should be updated if users modify the mesh in some way.
- [ ] write more tests (especially for grids with multiple element types)
- [ ] Actually use this class in `interpWeighted`
- [ ] Ensure that constraints still work when we use direct array access. libMesh sometimes modifies the array of dof indices; I need to learn how this works.
- [ ] Consider whether or not we should use a more sophisticated scattering routine instead of simply using the ghost indices directly. Would it be compatible with libMesh's constraint implementation?
- [ ] move the implementation into `FEDataManager.cpp`
- [ ] Implement a 'scratch' array function inside `SystemPatchDataView` that manages an array, indexed in the same way as the index arrays, with float data (we would use this with `get_values_for_interpolation`)
- [ ] Compute the number of dofs per cell by subtracting the index array entries instead of storing it directly

### CODE REVIEW

**Comment by boyceg** [comment]
One thing to be careful about is that SAMRAI has a "PatchData" concept, and so we want to make sure that it is very clear that FEPatchData is not this kind of patch data.

Also, if you are storing data in a way that is indexed by the SAMRAI cell indexing scheme ... would it make sense to go ahead and make it use the SAMRAI PatchData interface, so that SAMRAI can communicate the cached info when we reconstruct the AMR grid hierarchy? This could possibly simplify parallel redistribution, by allowing the code to simply look at the local libMesh element or node indices when setting up the libMesh partitioning.

**Comment by drwells** [comment]
Yeah, the names for these classes are not great: there is really no relation to SAMRAI other than 'these elements have support on the given patch'.

**Comment by drwells** [comment]
It may not be possible to store libMesh indices inside SAMRAI in an efficient way since we want to continue supporting meshes with multiple element types. We could definitely store the element ids, though.

**Comment by drwells** [comment]
Lets keep the branch, but at the moment this is not a significant bottleneck so I don't think it worth worrying about in the near future.

**Pull request closed without merging**
