### PR TITLE
Fix Omega_idx error in INSVCStaggeredHierarchyIntegrator class

### PR DESCRIPTION
**Pull request by Raamkrishnan**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format (i.e., `make indent`) run? For more information see
      `scripts/formatting/README.md`.
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [ ] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [ ] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

If we deallocate ```d_Omega_idx``` after tagging cells in ```applyGradientDetectorSpecialized``` of ```INSVCStaggeredHierarchyIntegrator``` class, then we need to allocate ```d_Omega_idx``` again in   ```setupPlotDataSpecialized``` to use it for plotting purposes. So I am not deallocating ```d_Omega_idx```. Another way is to allocate and deallocate ```d_Omega_idx``` within the ```setupPlotDataSpecialized``` function. To test this, I modified the ```tests/multiphase_flow/high_density_droplet case``` to use an AMR grid.

### CODE REVIEW

**Review by amneetb — APPROVED** [review]

**Comment by amneetb** [comment]
@drwells: Can you take a second look at this PR?

**Comment by Raamkrishnan** [comment]
I’m adding a test which will consider minor change in FlowGravityForcing
class also. I will push the test today to this patch. Then we can take a
look at the changes and merge it.

Best,
Rama

**Comment by Raamkrishnan** [comment]
I have converted multiphase_flow/ex10 (water entry of a circular cylinder) into a test. This patch also removes a minor bug in the ```vc_ins_utilities``` class. Please take a look. I will add a changelog after the review.

**Comment by amneetb** [comment]
@Raamkrishnan : looks good. Thanks!

@drwells : Can you take a look and approve? @Raamkrishnan will rebase PRs #1627 and #1628. He is moving to another position by the end of this month. Would be great if he is able to rebase and merge his pending PRs before he leaves.

**Review by drwells — APPROVED** [review]

**Comment by drwells** [comment]
Thanks!

In the future could you open separate PRs for independent fixes?

**Comment by Raamkrishnan** [comment]
Sure I will do that. Thanks.

**Pull request merged**
