### PR TITLE
NWT: multiphase_flow examples 10, 11, 12, and 13

### PR DESCRIPTION
**Pull request by drwells**
Part of #546. As mentioned in #546 we cannot merge this until `ConstraintIBMethod::getFullLagrangeMultiplierForce` and `ConstraintIBMethod::getInterpolatedLagrangianDensity` are in the library: hence this is do not merge until we get that done.

### CODE REVIEW

**Comment by drwells** [comment]
I am also not in love with the large files added in this PR. Is there a way to shrink these?

**Comment by drwells** [comment]
I applied the same trick as in #547 so these examples should now compile. I also included all subsequent changes to these examples.

**Comment by drwells** [comment]
I just rebased this on top of master to get the `ln` fix in #551.

**Comment by amneetb** [comment]
We can also think about hosting geometry files (which maybe binary in nature) on a URL and `wget`-ing them during the build process. That will be perhaps more flexible.

**Comment by drwells** [comment]
I would very much prefer to not require network access during the build (this might not work if people are at airports or otherwise don't have Internet access (this can also be an issue on clusters). It also brings up the requirement of pairing a CDN with everything else we need.

We should just translate the other matlab scripts to C++ or Python and run them at build time. I rewrote the cylinder one in C++ and am trying to figure out how to do the barge too.

**Comment by amneetb** [comment]
@drwells : Good point.

**Comment by amneetb** [comment]
https://www.mathworks.com/videos/automatically-converting-matlab-code-to-c-code-96483.html

**Comment by amneetb** [comment]
> https://www.mathworks.com/videos/automatically-converting-matlab-code-to-c-code-96483.html

I just tried this. It is not that straightforward :-(

**Comment by drwells** [comment]
I have never gotten these things to work well.

It only took me about 30 minutes to get the cylinder one converted and ten minutes for the barge. These are not complex matlab scripts.

**Comment by drwells** [comment]
ex11 needs https://github.com/IBAMR/IBAMR/commit/c188e2116d2ed7fc05bec29412573dfd0c775483 to work correctly.

**Comment by amneetb** [comment]
Let me know when #550 is fixed for the test I added and merged with #548. I will work on ex11 and its test.

**Comment by boyceg** [comment]
> Let me know when #550 is fixed for the test I added and merged with #548. I will work on ex11 and its test.

@amneetb give this a try now.

**Comment by boyceg** [comment]
@amneetb, the tests are (finally) back.

Once this is done, I will set up the final branches related to the core functionality from NWT branch.

**Comment by drwells** [comment]
We still need to finish #567 before we can merge this.

**Comment by amneetb** [comment]
This can be wrapped up now(?)

**Comment by drwells** [comment]
We need to regenerate `configure`: let me do that. Otherwise we can merge this once we fix the test in #567 (and merge it).

**Comment by drwells** [comment]
`configure` is up to date so we can push the button once #567 is in :)

**Comment by drwells** [comment]
We are still missing some more input files. I am writing the extra grid generation programs now.

**Comment by drwells** [comment]
OK, we have the extra grid generation programs. I just checked that everything is automatically generated correctly.

Since this has previously been approved lets merge.

**Comment by drwells** [comment]
I just noticed after this that the hash is different on my machine. Let me fix this..

**Pull request merged**
