### PR TITLE
Fix test partitioning

### LINKED ISSUE #773: Get the test suite working on my desktop
Subj.

For whatever reason, I get different results for some tests on my workstation than I do on my personal desktop. Some of the differences (like for linear spreading and interpolation) are quite large. Some are very small: e.g., one processor will have one more quadrature point and another will have one less. I will get this sorted out before the release.

### PR DESCRIPTION
**Pull request by drwells**
This is enough of a fix for #773 for now. It would be nice to solve the root problem and get SAMRAI to deterministically initially partition patches but I doubt that this is possible from inside IBAMR - hopefully it has been fixed in a more recent release.

Fixes #773.

### CODE REVIEW

**Comment by drwells** [comment]
@abarret if you have time could you rerun the testsuite with this patch? This should fix the IBFE tests.

**Comment by abarret** [comment]
This fixes the `IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input` test for me.

**Comment by boyceg** [comment]
Does this show up for both `GREEDY` and `SPATIAL` bin packing algorithms?

**Comment by drwells** [comment]
Yup.

**Comment by boyceg** [comment]
Only with AMR?

**Comment by drwells** [comment]
AFAICT yes - if we just have a single nonrefined grid then each processor gets an equally-sized chunk of that grid regardless of the machine used.

**Comment by drwells** [comment]
Additionally, those chunks are distributed in the same way - e.g., processor 2 always gets (8, 8) - (15, 15).

**Comment by drwells** [comment]
@boyceg This patch isn't perfect but its good enough for the release. Is there anything else you would like to change?

**Pull request merged**
