### PR TITLE
Fix CIBStaggeredStokesOperator for multi-patch domains

### PR DESCRIPTION
**Pull request by boyceg**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

Related to #906.

### CODE REVIEW

**Comment by boyceg** [comment]
@amneetb, @fuhuifang, I think this should fix the parallel CIB issues.

@amneetb could you set up some simple 2D and 3D tests for CIB in serial and parallel? Please feel free to commit directly to the branch.

**Comment by drwells** [comment]
Looks good at a glance :+1: Let me try running it :)

**Comment by boyceg** [comment]
I'm also running the testsuite right now.

**Comment by drwells** [comment]
Are you happy with this @boyceg? If so lets merge.

**Comment by boyceg** [comment]
Sure.

**Pull request merged**
