### PR TITLE
Remove gsl

### LINKED ISSUE #1358: Convert the GSL integrals to use boost
boost 1.66 was released in 2017 and it includes support for Gauss-Kronrod quadrature (the quadrature we use in eel3d):

https://www.boost.org/users/history/version_1_66_0.html

I'd like to update our minimum and bundled versions of boost so we can use this instead of GSL - this way users don't need one more dependency just to run this example.

AFAICT we only use GSL in this one place and we should be able to convert it pretty easily to use the boost version instead. Thoughts?

### PR DESCRIPTION
**Pull request by drwells**
Fixes #1358. Depends on #1362 (we don't want to bundle a version of boost that is too old).

I ran a thousand or so timesteps with the eel3d code to verify that this doesn't introduce large changes - the transverse velocity changes at the solver tolerance level (about O(10^-11)) but otherwise things are identical.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

**Comment by amneetb** [comment]
Looks good. Another test could be comparing the vertex file generated by new and old eelgenerator.cpp. Also, I think we should keep gsl.m4 just in case somebody wants to use GSL in an application?

**Comment by boyceg** [comment]
> Looks good. Another test could be comparing the vertex file generated by new and old eelgenerator.cpp. Also, I think we should keep gsl.m4 just in case somebody wants to use GSL in an application?

I think that I would prefer to drop `gsl.m4` if we don't use it anywhere in the library, examples, or tests --- seems easy to accidentally break.

**Comment by amneetb** [comment]
Perhaps boost already supports most of the gsl features, so we can remove it.

**Comment by drwells** [comment]
@amneetb I think we now have this - I added a test

tests/external/eelgenerator3d.cpp

in this PR that checks that we really do get the same results for both.

**Pull request merged**
