### PR TITLE
use PetscVector::get_array_read() to access local form arrays in FEDataManager

### PR DESCRIPTION
**Pull request by boyceg**
This PR includes the parts of #450 that @drwells likes and omits the parts that he doesn't.

### CODE REVIEW

**Comment by boyceg** [comment]
Can you run callgrind to see if this addresses the large numbers of calls to `PetscCheckPointer`?

**Comment by drwells** [comment]
The changes in FEDataManager should do this if they were the same as my original patch. I will check.

**Comment by drwells** [comment]
Recompiling this on my laptop is going to take close to an hour so I'll verify this in the morning.

**Comment by drwells** [comment]
We eliminated about 99% of the calls to `VecGetRange`, which in turn eliminated about half the calls to `PetscCheckPointer`. Its not perfect, but it is now much less prominent in the profiling results.

**Comment by knepley** [comment]
@boyceg @drwells Did you guys run with -check_pointer_intensity 0 in order to turn off the pointer checks?

**Comment by boyceg** [comment]
I haven't yet, although @drwells is running most of these checks. They do not show up prominently in the Apple Time Profiler runs that I have done.

**Comment by drwells** [comment]
@knepley I do not see any changes when running with `-check_pointer_intensity 0` as a command line argument: the callgrind results don't change at all when I add that.

**Comment by knepley** [comment]
Do you mean time or number of calls? We see significant time savings on hot routines. That is strange if you see nothing.

**Comment by drwells** [comment]
I saw absolutely no difference in either when executing the test program as

```
valgrind --tool=callgrind ./main3d ./input3d -check_pointer_intensity 0
```

**Pull request merged**
