### PR TITLE
Replace empty special member functions with = default.

### PR DESCRIPTION
**Pull request by abarret**
Last c++11 update.

Note that there were four files that have been deleted since they are now empty.

### CODE REVIEW

**Comment by boyceg** [comment]
@abarret is the reigning champion of removing LOC!

**Comment by boyceg** [comment]
This is good to merge once @drwells and Jenkins give the 👍.

**Comment by abarret** [comment]
My goal is to forever have a net negative impact on LOC.

**Comment by drwells** [comment]
If you believe https://github.com/IBAMR/IBAMR/graphs/contributors then @abarret has removed 319,000 more lines than he has added, and with this PR his lead is only widening :)

We actually removed some files this time; not bad.

**Comment by drwells** [comment]
It looks like we need to add
```cpp
#include "ibamr/INSVCStaggeredConservativeMassMomentumIntegrator.h"
```

to `INSVCStaggeredConservativeHierarchyIntegrator.cpp`.

**Comment by boyceg** [comment]
You wanna squash before I merge?

**Pull request merged**
