### PR TITLE
Clean up macro definitions

### LINKED ISSUE #610: Add macros to suppress warnings in external libraries
I have read enough deprecation warnings about `std::binder1st` inside Eigen. We should add some macros to disable these warnings around all of our third-party library inclusions. This is pretty easy to do: we should simply borrow deal.II's nice macro:
```cpp

/***********************************************************************
 * Two macros to guard external header includes.
 *
 * Selectively disable diagnostics set by "-Wextra" (and similar flags) for
 * GCC and compiler accepting GCC dialects (such as clang).
 * "diagnostic push" is supported since gcc-4.6 and clang-3.3.
 */

#ifdef DEAL_II_COMPILER_HAS_DIAGNOSTIC_PRAGMA

/* keep pragmas with an exclamation mark in order.. */
#  define DEAL_II_DISABLE_EXTRA_DIAGNOSTICS                             \
_Pragma("GCC diagnostic push")                                    /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wunknown-pragmas\"")           /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wpragmas\"")                   /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wunknown-warning-option\"")    /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wunknown-warning\"")           /*!*/ \
_Pragma("GCC diagnostic ignored \"-Wextra\"")                     /*!*/ \
_Pragma("GCC diagnostic ignored \"-Waddress-of-packed-member\"")        \
_Pragma("GCC diagnostic ignored \"-Wdeprecated-copy\"")                 \
_Pragma("GCC diagnostic ignored \"-Wdeprecated-declarations\"")         \
_Pragma("GCC diagnostic ignored \"-Wexpansion-to-defined\"")            \
_Pragma("GCC diagnostic ignored \"-Wexpansion-to-defined\"")            \
_Pragma("GCC diagnostic ignored \"-Wignored-attributes\"")              \
_Pragma("GCC diagnostic ignored \"-Wignored-qualifiers\"")              \
_Pragma("GCC diagnostic ignored \"-Wimplicit-fallthrough\"")            \
_Pragma("GCC diagnostic ignored \"-Winfinite-recursion\"")              \
_Pragma("GCC diagnostic ignored \"-Wint-in-bool-context\"")             \
_Pragma("GCC diagnostic ignored \"-Wmisleading-indentation\"")          \
_Pragma("GCC diagnostic ignored \"-Wmissing-field-initializers\"")      \
_Pragma("GCC diagnostic ignored \"-Wnested-anon-types\"")               \
_Pragma("GCC diagnostic ignored \"-Wnon-virtual-dtor\"")                \
_Pragma("GCC diagnostic ignored \"-Woverflow\"")                        \
_Pragma("GCC diagnostic ignored \"-Woverloaded-virtual\"")              \
_Pragma("GCC diagnostic ignored \"-Wpedantic\"")                        \
_Pragma("GCC diagnostic ignored \"-Wtautological-constant-out-of-range-compare\"") \
_Pragma("GCC diagnostic ignored \"-Wtype-limits\"")                     \
_Pragma("GCC diagnostic ignored \"-Wundef\"")                           \
_Pragma("GCC diagnostic ignored \"-Wunused-but-set-parameter\"")        \
_Pragma("GCC diagnostic ignored \"-Wunused-but-set-variable\"")         \
_Pragma("GCC diagnostic ignored \"-Wunused-function\"")                 \
_Pragma("GCC diagnostic ignored \"-Wunused-parameter\"")                \
_Pragma("GCC diagnostic ignored \"-Wunused-private-field\"")            \
_Pragma("GCC diagnostic ignored \"-Wunused-variable\"")                 \
_Pragma("GCC diagnostic warning \"-Wpragmas\"")                   /*!*/

#  define DEAL_II_ENABLE_EXTRA_DIAGNOSTICS                              \
_Pragma("GCC diagnostic pop")

#else

#  define DEAL_II_DISABLE_EXTRA_DIAGNOSTICS
#  define DEAL_II_ENABLE_EXTRA_DIAGNOSTICS

#endif
```
and put it in our own configuration header (and, of course, `s/DEAL_II/IBAMR/`).

### PR DESCRIPTION
**Pull request by drwells**
Fixes #610: we no longer print thousands of totally irrelevant Eigen warnings with newer GCC compilers.

While `_Pragma` is a keyword in C++11 (so this should always work), I added a test for it anyway to make sure all our compilers can, in fact, successfully compile `_Pragma("GCC diagnostic pop")` et al to be sure.

### CODE REVIEW

**Comment by drwells** [comment]
Ooh, good idea. I'll push an improvement in a moment.

**Comment by drwells** [comment]
Actually, while we are at it, let me take this opportunity to spend a little time cleaning up and sorting our `#include`s. It will take a bit longer but we might as well fix the order of our headers while we massively rearrange.

**Comment by boyceg** [comment]
Shouldn’t clang-format accomplish this for us?

**Comment by drwells** [comment]
Yup: we can instruct it to sort the headers for us. I plan on doing exactly that and then adding the guards.

**Comment by drwells** [comment]
I added code to disable similar warnings in boost. Its hard to know exactly what warnings people will run into, but we can add that as we go along.

**Comment by drwells** [comment]
@boyceg are you happy with this? If so lets merge.

I suspect that we will want to add a few more `_Pragma` statements over time but its hard to know, without using a bunch of different compilers and versions of external libraries, what we should add.

**Pull request merged**
